In [1]:
import pandas as pd
path_1 = 'datasets/cities_crosswalk.csv'
path_2 = 'datasets/City_time_series.csv'
path_3 = 'datasets/County_time_series.csv'
path_4 = 'datasets/CountyCrossWalk_Zillow.csv'
path_5 = 'datasets/DataDictionary.csv'
path_6 = 'datasets/Neighborhood_time_series.csv'
path_7 = 'datasets/State_time_series.csv'
path_8 = 'datasets/Zip_time_series.csv'
path_9 = 'datasets/Metro_time_series.csv'

In [2]:
country_cross_walk = pd.read_csv(path_4)

In [3]:
country_cross_walk = country_cross_walk.rename(columns={'CountyName': 'County'})

In [4]:
country_cross_walk

,County,StateName,StateFIPS,CountyFIPS,MetroName_Zillow,CBSAName,CountyRegionID_Zillow,MetroRegionID_Zillow,FIPS,CBSACode
0,Pike,Pennsylvania,42,103,"New York, NY","New York-Newark-Jersey City, NY-NJ-PA",280,394913.0,42103,35620.0
1,Bronx,New York,36,5,"New York, NY","New York-Newark-Jersey City, NY-NJ-PA",401,394913.0,36005,35620.0
2,Essex,New Jersey,34,13,"New York, NY","New York-Newark-Jersey City, NY-NJ-PA",504,394913.0,34013,35620.0
3,Kings,New York,36,47,"New York, NY","New York-Newark-Jersey City, NY-NJ-PA",581,394913.0,36047,35620.0
4,Ocean,New Jersey,34,29,"New York, NY","New York-Newark-Jersey City, NY-NJ-PA",659,394913.0,34029,35620.0
5,Union,New Jersey,34,39,"New York, NY","New York-Newark-Jersey City, NY-NJ-PA",771,394913.0,34039,35620.0
6,Bergen,New Jersey,34,3,"New York, NY","New York-Newark-Jersey City, NY-NJ-PA",874,394913.0,34003,35620.0
7,Hudson,New Jersey,34,17,"New York, NY","New York-Newark-Jersey City, NY-NJ-PA",1106,394913.0,34017,35620.0
8,Morris,New Jersey,34,27,"New York, NY","New York-Newark-Jersey City, NY-NJ-PA",1241,394913.0,34027,35620.0
9,Nassau,New York,36,59,"New York, NY","New York-Newark-Jersey City, NY-NJ-PA",1252,394913.0,36059,35620.0
10,Orange,New York,36,71,"New York, NY","New York-Newark-Jersey City, NY-NJ-PA",1290,394913.0,36071,35620.0
11,Putnam,New York,36,79,"New York, NY","New York-Newark-Jersey City, NY-NJ-PA",1343,394913.0,36079,35620.0
12,Queens,New York,36,81,"New York, NY","New York-Newark-Jersey City, NY-NJ-PA",1347,394913.0,36081,35620.0
13,Sussex,New Jersey,34,37,"New York, NY","New York-Newark-Jersey City, NY-NJ-PA",1413,394913.0,34037,35620.0
14,Passaic,New Jersey,34,31,"New York, NY","New York-Newark-Jersey City, NY-NJ-PA",1964,394913.0,34031,35620.0
15,Suffolk,New York,36,103,"New York, NY","New York-Newark-Jersey City, NY-NJ-PA",2046,394913.0,36103,35620.0
16,Dutchess,New York,36,27,"New York, NY","New York-Newark-Jersey City, NY-NJ-PA",2255,394913.0,36027,35620.0
17,Monmouth,New Jersey,34,25,"New York, NY","New York-Newark-Jersey City, NY-NJ-PA",2441,394913.0,34025,35620.0
18,New York,New York,36,61,"New York, NY","New York-Newark-Jersey City, NY-NJ-PA",2452,394913.0,36061,35620.0
19,Richmond,New York,36,85,"New York, NY","New York-Newark-Jersey City, NY-NJ-PA",2511,394913.0,36085,35620.0
20,Rockland,New York,36,87,"New York, NY","New York-Newark-Jersey City, NY-NJ-PA",2515,394913.0,36087,35620.0
21,Somerset,New Jersey,34,35,"New York, NY","New York-Newark-Jersey City, NY-NJ-PA",2552,394913.0,34035,35620.0
22,Hunterdon,New Jersey,34,19,"New York, NY","New York-Newark-Jersey City, NY-NJ-PA",2729,394913.0,34019,35620.0
23,Middlesex,New Jersey,34,23,"New York, NY","New York-Newark-Jersey City, NY-NJ-PA",2802,394913.0,34023,35620.0
24,Westchester,New York,36,119,"New York, NY","New York-Newark-Jersey City, NY-NJ-PA",3148,394913.0,36119,35620.0
25,Los Angeles,California,6,37,"Los Angeles-Long Beach-Anaheim, CA","Los Angeles-Long Beach-Anaheim, CA",3101,753899.0,6037,31080.0
26,Orange,California,6,59,"Los Angeles-Long Beach-Anaheim, CA","Los Angeles-Long Beach-Anaheim, CA",1286,753899.0,6059,31080.0
27,Porter,Indiana,18,127,"Chicago, IL","Chicago-Naperville-Elgin, IL-IN-WI",1330,394463.0,18127,16980.0
28,De Kalb,Illinois,17,37,"Chicago, IL","Chicago-Naperville-Elgin, IL-IN-WI",1657,394463.0,17037,16980.0
29,Du Page,Illinois,17,43,"Chicago, IL","Chicago-Naperville-Elgin, IL-IN-WI",1682,394463.0,17043,16980.0
...,...,...,...,...,...,...,...,...,...,...
3114,Dixie,Florida,12,29,NaN,NaN,480,NaN,12029,NaN
3115,Clark,Idaho,16,33,NaN,NaN,439,NaN,16033,NaN
3116,Clark,Illinois,17,23,NaN,NaN,440,NaN,17023,NaN
3117,Casey,Kentucky,21,45,NaN,NaN,427,NaN,21045,NaN
3118,Clark,Kansas,20,25,NaN,NaN,442,NaN,20025,NaN
3119,Caddo,Oklahoma,40,15,NaN,NaN,424,NaN,40015,NaN
3120,Cedar,Iowa,19,31,NaN,NaN,430,NaN,19031,NaN
3121,Cedar,Missouri,29,39,NaN,NaN,431,NaN,29039,NaN
3122,Cedar,Nebraska,31,27,NaN,NaN,432,NaN,31027,NaN
3123,Chase,Kansas,20,17,NaN,NaN,434,NaN,20017,NaN
3124,Chase,Nebraska,31,29,NaN,NaN,435,NaN,31029,NaN
3125,Clare,Michigan,26,35,NaN,NaN,437,NaN,26035,NaN
3126,Brown,Nebraska,31,17,NaN,NaN,406,NaN,31017,NaN
3127,Brown,South Dakota,46,13,NaN,"Aberdeen, SD",408,394297.0,46013,10100.0
3128,Brule,South Dakota,46,15,NaN,NaN,411,NaN,46015,NaN
3129,Butte,South Dakota,46,19,NaN,NaN,420,NaN,46019,NaN
3130,Burke,North Dakota,38,13,NaN,NaN,417,NaN,38013,NaN
3131,Bland,Virginia,51,21,NaN,NaN,388,NaN,51021,NaN
3132,Boone,Nebraska,31,11,NaN,NaN,396,NaN,31011,NaN
3133,Brown,Kansas,20,13,NaN,NaN,404,NaN,20013,NaN
3134,Brown,Illinois,17,9,NaN,NaN,402,NaN,17009,NaN
3135,Barry,Missouri,29,9,NaN,NaN,383,NaN,29009,NaN
3136,Baker,Oregon,41,1,NaN,NaN,380,NaN,41001,NaN
3137,Banks,Georgia,13,11,NaN,NaN,381,NaN,13011,NaN
3138,Allen,Louisiana,22,3,NaN,NaN,370,NaN,22003,NaN
3139,Allen,Kansas,20,1,NaN,NaN,368,NaN,20001,NaN
3140,Anson,North Carolina,37,7,NaN,NaN,374,NaN,37007,NaN
3141,Atoka,Oklahoma,40,5,NaN,NaN,375,NaN,40005,NaN
3142,Avery,North Carolina,37,11,NaN,NaN,376,NaN,37011,NaN
3143,Bacon,Georgia,13,5,NaN,NaN,377,NaN,13005,NaN

In [5]:
unemployment_by_county = pd.read_csv('datasets/unemployment-by-county-us/output.csv')

In [6]:
unemployment_by_county

        Year     Month        State                  County  Rate
0       2015  February  Mississippi           Newton County   6.1
1       2015  February  Mississippi           Panola County   9.4
2       2015  February  Mississippi           Monroe County   7.9
3       2015  February  Mississippi            Hinds County   6.1
4       2015  February  Mississippi           Kemper County  10.6
5       2015  February  Mississippi          Calhoun County   6.9
6       2015  February  Mississippi           Clarke County   7.9
7       2015  February  Mississippi        Jefferson County  14.3
8       2015  February  Mississippi          Madison County   4.5
9       2015  February  Mississippi          Sharkey County  11.1
10      2015  February  Mississippi           Tunica County  11.5
11      2015  February  Mississippi             Tate County   7.6
12      2015  February  Mississippi        Lafayette County   5.5
13      2015  February  Mississippi          Bolivar County   8.6
14      2015  February  Mississippi            Stone County   7.6
15      2015  February  Mississippi          Noxubee County  10.6
16      2015  February  Mississippi            Lamar County   4.7
17      2015  February  Mississippi              Lee County   5.9
18      2015  February  Mississippi           Desoto County   5.0
19      2015  February  Mississippi            Adams County   7.6
20      2015  February  Mississippi         Pontotoc County   5.9
21      2015  February  Mississippi           Marion County   7.4
22      2015  February  Mississippi           Jasper County   7.5
23      2015  February  Mississippi          Simpson County   5.7
24      2015  February  Mississippi        Sunflower County  12.6
25      2015  February  Mississippi          Hancock County   6.6
26      2015  February  Mississippi          Winston County   8.3
27      2015  February  Mississippi          Carroll County   8.5
28      2015  February  Mississippi           Copiah County   7.6
29      2015  February  Mississippi  Jefferson Davis County   8.2
...      ...       ...          ...                     ...   ...
885518  2009  November       Nevada             Elko County   6.3
885519  2009  November       Nevada          Lincoln County   9.5
885520  2009  November       Nevada           Eureka County   6.9
885521  2009  November       Nevada           Lander County   5.9
885522  2009  November       Nevada          Mineral County   8.9
885523  2009  November       Nevada          Douglas County  12.5
885524  2009  November       Nevada        Esmeralda County   6.9
885525  2009  November       Nevada           Washoe County  11.5
885526  2009  November       Nevada           Storey County  12.5
885527  2009  November       Nevada             Lyon County  15.8
885528  2009  November       Nevada        Churchill County   9.1
885529  2009  November       Nevada       White Pine County   7.3
885530  2009  November       Nevada            Clark County  12.5
885531  2009  November       Nevada         Pershing County   9.9
885532  2009  November        Maine         Kennebec County   7.3
885533  2009  November        Maine          Hancock County   9.0
885534  2009  November        Maine     Androscoggin County   8.0
885535  2009  November        Maine       Cumberland County   6.6
885536  2009  November        Maine        Sagadahoc County   7.0
885537  2009  November        Maine          Lincoln County   7.7
885538  2009  November        Maine       Washington County   9.2
885539  2009  November        Maine             York County   7.8
885540  2009  November        Maine            Waldo County   8.7
885541  2009  November        Maine        Penobscot County   7.8
885542  2009  November        Maine         Franklin County  10.2
885543  2009  November        Maine         Somerset County  10.5
885544  2009  November        Maine           Oxford County  10.5
885545  2009  November        Maine             Knox County   7.5
885546  2009  November        Maine      Piscataquis County  11.3
885547  2009  November        Maine        Aroostook County   9.0

[885548 rows x 5 columns]

In [7]:
unemployment_monthly_data = pd.merge(unemployment_by_county, country_cross_walk, how='left')

In [8]:
unemployment_monthly_data = unemployment_monthly_data.rename(columns={'Rate': 'Unemployment Rate'})

In [9]:
unemployment_monthly_data

,Year,Month,State,County,Unemployment Rate,StateName,StateFIPS,CountyFIPS,MetroName_Zillow,CBSAName,CountyRegionID_Zillow,MetroRegionID_Zillow,FIPS,CBSACode
0,2015,February,Mississippi,Newton County,6.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2015,February,Mississippi,Panola County,9.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2015,February,Mississippi,Monroe County,7.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2015,February,Mississippi,Hinds County,6.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2015,February,Mississippi,Kemper County,10.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2015,February,Mississippi,Calhoun County,6.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2015,February,Mississippi,Clarke County,7.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2015,February,Mississippi,Jefferson County,14.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2015,February,Mississippi,Madison County,4.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2015,February,Mississippi,Sharkey County,11.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2015,February,Mississippi,Tunica County,11.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2015,February,Mississippi,Tate County,7.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2015,February,Mississippi,Lafayette County,5.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2015,February,Mississippi,Bolivar County,8.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,2015,February,Mississippi,Stone County,7.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,2015,February,Mississippi,Noxubee County,10.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,2015,February,Mississippi,Lamar County,4.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,2015,February,Mississippi,Lee County,5.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,2015,February,Mississippi,Desoto County,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,2015,February,Mississippi,Adams County,7.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,2015,February,Mississippi,Pontotoc County,5.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,2015,February,Mississippi,Marion County,7.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,2015,February,Mississippi,Jasper County,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,2015,February,Mississippi,Simpson County,5.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,2015,February,Mississippi,Sunflower County,12.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,2015,February,Mississippi,Hancock County,6.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,2015,February,Mississippi,Winston County,8.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,2015,February,Mississippi,Carroll County,8.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,2015,February,Mississippi,Copiah County,7.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,2015,February,Mississippi,Jefferson Davis County,8.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
885518,2009,November,Nevada,Elko County,6.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
885519,2009,November,Nevada,Lincoln County,9.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
885520,2009,November,Nevada,Eureka County,6.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
885521,2009,November,Nevada,Lander County,5.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
885522,2009,November,Nevada,Mineral County,8.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
885523,2009,November,Nevada,Douglas County,12.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
885524,2009,November,Nevada,Esmeralda County,6.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
885525,2009,November,Nevada,Washoe County,11.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
885526,2009,November,Nevada,Storey County,12.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
885527,2009,November,Nevada,Lyon County,15.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
885528,2009,November,Nevada,Churchill County,9.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
885529,2009,November,Nevada,White Pine County,7.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
885530,2009,November,Nevada,Clark County,12.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
885531,2009,November,Nevada,Pershing County,9.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
885532,2009,November,Maine,Kennebec County,7.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
885533,2009,November,Maine,Hancock County,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
885534,2009,November,Maine,Androscoggin County,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
885535,2009,November,Maine,Cumberland County,6.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
885536,2009,November,Maine,Sagadahoc County,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
885537,2009,November,Maine,Lincoln County,7.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
885538,2009,November,Maine,Washington County,9.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
885539,2009,November,Maine,York County,7.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
885540,2009,November,Maine,Waldo County,8.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
885541,2009,November,Maine,Penobscot County,7.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
885542,2009,November,Maine,Franklin County,10.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
885543,2009,November,Maine,Somerset County,10.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
885544,2009,November,Maine,Oxford County,10.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
885545,2009,November,Maine,Knox County,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
885546,2009,November,Maine,Piscataquis County,11.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
885547,2009,November,Maine,Aroostook County,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
unemployment_monthly_data = unemployment_monthly_data.dropna()

In [11]:
column_list = ['Year', 'Month', 'State', 'StateFIPS', 'MetroName_Zillow', 'CBSAName', 'MetroRegionID_Zillow', 'CBSACode']

In [12]:
for x in column_list:
    unemployment_monthly_data[x] = unemployment_monthly_data[x].astype(str)

C:\Users\kmcex\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [13]:
unemployment_monthly_data.groupby(column_list).mean()

                                                                                                                                  Unemployment Rate  \
Year Month     State    StateFIPS MetroName_Zillow    CBSAName                                     MetroRegionID_Zillow CBSACode
1990 April     Maryland 24.0      Baltimore, MD       Baltimore-Columbia-Towson, MD                394358.0             12580.0            6.500000
               Missouri 29.0      St. Louis, MO       St. Louis, MO-IL                             395121.0             41180.0            8.000000
               Nevada   32.0      Carson City, NV     Carson City, NV                              394444.0             16180.0            5.500000
               Virginia 51.0      Big Stone Gap, VA   Big Stone Gap, VA                            753866.0             13720.0            9.900000
                                  Blacksburg, VA      Blacksburg-Christiansburg-Radford, VA        394392.0             13980.0            9.400000
                                  Charlottesville, VA Charlottesville, VA                          394459.0             16820.0            1.700000
                                  Danville, VA        Danville, VA                                 394518.0             19260.0            9.400000
                                  Harrisonburg, VA    Harrisonburg, VA                             394668.0             25500.0            5.000000
                                  Kingsport, TN       Kingsport-Bristol-Bristol, TN-VA             394747.0             28700.0            6.600000
                                  Lynchburg, VA       Lynchburg, VA                                394811.0             31340.0            5.200000
                                  Martinsville, VA    Martinsville, VA                             394836.0             32300.0            6.200000
                                  Richmond, VA        Richmond, VA                                 395022.0             40060.0            5.200000
                                  Roanoke, VA         Roanoke, VA                                  395028.0             40220.0            3.350000
                                  Staunton, VA        Staunton-Waynesboro, VA                      395128.0             44420.0            3.350000
                                  Virginia Beach, VA  Virginia Beach-Norfolk-Newport News, VA-NC   395194.0             47260.0            4.811111
                                  Washington, DC      Washington-Arlington-Alexandria, DC-VA-MD-WV 395209.0             47900.0            2.166667
                                  Winchester, VA      Winchester, VA-WV                            395232.0             49020.0            5.500000
     August    Maryland 24.0      Baltimore, MD       Baltimore-Columbia-Towson, MD                394358.0             12580.0            8.200000
               Missouri 29.0      St. Louis, MO       St. Louis, MO-IL                             395121.0             41180.0            9.300000
               Nevada   32.0      Carson City, NV     Carson City, NV                              394444.0             16180.0            4.800000
               Virginia 51.0      Big Stone Gap, VA   Big Stone Gap, VA                            753866.0             13720.0            8.700000
                                  Blacksburg, VA      Blacksburg-Christiansburg-Radford, VA        394392.0             13980.0           13.300000
                                  Charlottesville, VA Charlottesville, VA                          394459.0             16820.0            3.200000
                                  Danville, VA        Danville, VA                                 394518.0             19260.0           10.300000
                                  Harrisonburg, VA    Harrisonburg, VA                             394668.0             25500.0            6.600000
                                  Kingsport, TN       Kingsport-Bristol-Bristol, TN-VA             394747.0             28700.0            8.700000
                                  Lynchburg, VA       Lynchburg, VA                                394811.0             31340.0            6.300000
                                  Martinsville, VA    Martinsville, VA                             394836.0             32300.0            6.600000
                                  Richmond, VA        Richmond, VA                                 395022.0             40060.0            6.300000
                                  Roanoke, VA         Roanoke, VA                                  395028.0             40220.0            3.900000
...                                                                                                                                             ...
2016 October   Virginia 51.0      Blacksburg, VA      Blacksburg-Christiansburg-Radford, VA        394392.0             13980.0            5.400000
                                  Charlottesville, VA Charlottesville, VA                          394459.0             16820.0            3.400000
                                  Danville, VA        Danville, VA                                 394518.0             19260.0            5.700000
                                  Harrisonburg, VA    Harrisonburg, VA                             394668.0             25500.0            5.000000
                                  Kingsport, TN       Kingsport-Bristol-Bristol, TN-VA             394747.0             28700.0            5.200000
                                  Lynchburg, VA       Lynchburg, VA                                394811.0             31340.0            5.200000
                                  Martinsville, VA    Martinsville, VA                             394836.0             32300.0            6.800000
                                  Richmond, VA        Richmond, VA                                 395022.0             40060.0            5.525000
                                  Roanoke, VA         Roanoke, VA                                  395028.0             40220.0            4.150000
                                  Staunton, VA        Staunton-Waynesboro, VA                      395128.0             44420.0            4.350000
                                  Virginia Beach, VA  Virginia Beach-Norfolk-Newport News, VA-NC   395194.0             47260.0            4.922222
                                  Washington, DC      Washington-Arlington-Alexandria, DC-VA-MD-WV 395209.0             47900.0            3.500000
                                  Winchester, VA      Winchester, VA-WV                            395232.0             49020.0            4.000000
     September Maryland 24.0      Baltimore, MD       Baltimore-Columbia-Towson, MD                394358.0             12580.0            5.800000
               Missouri 29.0      St. Louis, MO       St. Louis, MO-IL                             395121.0             41180.0            5.700000
               Nevada   32.0      Carson City, NV     Carson City, NV                              394444.0             16180.0            5.600000
               Virginia 51.0      Big Stone Gap, VA   Big Stone Gap, VA                            753866.0             13720.0            6.700000
                                  Blacksburg, VA      Blacksburg-Christiansburg-Radford, VA        394392.0             13980.0            5.200000
                                  Charlottesville, VA Charlottesville, VA                          394459.0             16820.0            3.300000
                                  Danville, VA        Danville, VA                                 394518.0             19260.0            5.800000
                                  Harrisonburg, VA    Harrisonburg, VA                             394668.0             25500.0            4.800000
                                  Kingsport, TN       Kingsport-Bristol-Bristol, TN-VA             394747.0             28700.0            5.400000
                                  Lynchburg, VA       Lynchburg, VA                                394811.0             31340.0            5.200000
                                  Martinsville, VA    Martinsville, VA                             394836.0             32300.0            6.800000
                                  Richmond, VA        Richmond, VA                                 395022.0             40060.0            5.625000
                                  Roanoke, VA         Roanoke, VA                                  395028.0             40220.0            4.100000
                                  Staunton, VA        Staunton-Waynesboro, VA                      395128.0             44420.0            4.150000
                                  Virginia Beach, VA  Virginia Beach-Norfolk-Newport News, VA-NC   395194.0             47260.0            4.888889
                                  Washington, DC      Washington-Arlington-Alexandria, DC-VA-MD-WV 395209.0             47900.0            3.416667
                                  Winchester, VA      Winchester, VA-WV                            395232.0             49020.0            3.900000

                                                                                                                                  CountyFIPS  \
Year Month     State    StateFIPS MetroName_Zillow    CBSAName                                     MetroRegionID_Zillow CBSACode
1990 April     Maryland 24.0      Baltimore, MD       Baltimore-Columbia-Towson, MD                394358.0             12580.0   510.000000
               Missouri 29.0      St. Louis, MO       St. Louis, MO-IL                             395121.0             41180.0   510.000000
               Nevada   32.0      Carson City, NV     Carson City, NV                              394444.0             16180.0   510.000000
               Virginia 51.0      Big Stone Gap, VA   Big Stone Gap, VA                            753866.0             13720.0   720.000000
                                  Blacksburg, VA      Blacksburg-Christiansburg-Radford, VA        394392.0             13980.0   750.000000
                                  Charlottesville, VA Charlottesville, VA                          394459.0             16820.0   540.000000
                                  Danville, VA        Danville, VA                                 394518.0             19260.0   590.000000
                                  Harrisonburg, VA    Harrisonburg, VA                             394668.0             25500.0   660.000000
                                  Kingsport, TN       Kingsport-Bristol-Bristol, TN-VA             394747.0             28700.0   520.000000
                                  Lynchburg, VA       Lynchburg, VA                                394811.0             31340.0   680.000000
                                  Martinsville, VA    Martinsville, VA                             394836.0             32300.0   690.000000
                                  Richmond, VA        Richmond, VA                                 395022.0             40060.0   682.500000
                                  Roanoke, VA         Roanoke, VA                                  395028.0             40220.0   772.500000
                                  Staunton, VA        Staunton-Waynesboro, VA                      395128.0             44420.0   805.000000
                                  Virginia Beach, VA  Virginia Beach-Norfolk-Newport News, VA-NC   395194.0             47260.0   725.000000
                                  Washington, DC      Washington-Arlington-Alexandria, DC-VA-MD-WV 395209.0             47900.0   619.666667
                                  Winchester, VA      Winchester, VA-WV                            395232.0             49020.0   840.000000
     August    Maryland 24.0      Baltimore, MD       Baltimore-Columbia-Towson, MD                394358.0             12580.0   510.000000
               Missouri 29.0      St. Louis, MO       St. Louis, MO-IL                             395121.0             41180.0   510.000000
               Nevada   32.0      Carson City, NV     Carson City, NV                              394444.0             16180.0   510.000000
               Virginia 51.0      Big Stone Gap, VA   Big Stone Gap, VA                            753866.0             13720.0   720.000000
                                  Blacksburg, VA      Blacksburg-Christiansburg-Radford, VA        394392.0             13980.0   750.000000
                                  Charlottesville, VA Charlottesville, VA                          394459.0             16820.0   540.000000
                                  Danville, VA        Danville, VA                                 394518.0             19260.0   590.000000
                                  Harrisonburg, VA    Harrisonburg, VA                             394668.0             25500.0   660.000000
                                  Kingsport, TN       Kingsport-Bristol-Bristol, TN-VA             394747.0             28700.0   520.000000
                                  Lynchburg, VA       Lynchburg, VA                                394811.0             31340.0   680.000000
                                  Martinsville, VA    Martinsville, VA                             394836.0             32300.0   690.000000
                                  Richmond, VA        Richmond, VA                                 395022.0             40060.0   682.500000
                                  Roanoke, VA         Roanoke, VA                                  395028.0             40220.0   772.500000
...                                                                                                                                      ...
2016 October   Virginia 51.0      Blacksburg, VA      Blacksburg-Christiansburg-Radford, VA        394392.0             13980.0   750.000000
                                  Charlottesville, VA Charlottesville, VA                          394459.0             16820.0   540.000000
                                  Danville, VA        Danville, VA                                 394518.0             19260.0   590.000000
                                  Harrisonburg, VA    Harrisonburg, VA                             394668.0             25500.0   660.000000
                                  Kingsport, TN       Kingsport-Bristol-Bristol, TN-VA             394747.0             28700.0   520.000000
                                  Lynchburg, VA       Lynchburg, VA                                394811.0             31340.0   680.000000
                                  Martinsville, VA    Martinsville, VA                             394836.0             32300.0   690.000000
                                  Richmond, VA        Richmond, VA                                 395022.0             40060.0   682.500000
                                  Roanoke, VA         Roanoke, VA                                  395028.0             40220.0   772.500000
                                  Staunton, VA        Staunton-Waynesboro, VA                      395128.0             44420.0   805.000000
                                  Virginia Beach, VA  Virginia Beach-Norfolk-Newport News, VA-NC   395194.0             47260.0   725.000000
                                  Washington, DC      Washington-Arlington-Alexandria, DC-VA-MD-WV 395209.0             47900.0   619.666667
                                  Winchester, VA      Winchester, VA-WV                            395232.0             49020.0   840.000000
     September Maryland 24.0      Baltimore, MD       Baltimore-Columbia-Towson, MD                394358.0             12580.0   510.000000
               Missouri 29.0      St. Louis, MO       St. Louis, MO-IL                             395121.0             41180.0   510.000000
               Nevada   32.0      Carson City, NV     Carson City, NV                              394444.0             16180.0   510.000000
               Virginia 51.0      Big Stone Gap, VA   Big Stone Gap, VA                            753866.0             13720.0   720.000000
                                  Blacksburg, VA      Blacksburg-Christiansburg-Radford, VA        394392.0             13980.0   750.000000
                                  Charlottesville, VA Charlottesville, VA                          394459.0             16820.0   540.000000
                                  Danville, VA        Danville, VA                                 394518.0             19260.0   590.000000
                                  Harrisonburg, VA    Harrisonburg, VA                             394668.0             25500.0   660.000000
                                  Kingsport, TN       Kingsport-Bristol-Bristol, TN-VA             394747.0             28700.0   520.000000
                                  Lynchburg, VA       Lynchburg, VA                                394811.0             31340.0   680.000000
                                  Martinsville, VA    Martinsville, VA                             394836.0             32300.0   690.000000
                                  Richmond, VA        Richmond, VA                                 395022.0             40060.0   682.500000
                                  Roanoke, VA         Roanoke, VA                                  395028.0             40220.0   772.500000
                                  Staunton, VA        Staunton-Waynesboro, VA                      395128.0             44420.0   805.000000
                                  Virginia Beach, VA  Virginia Beach-Norfolk-Newport News, VA-NC   395194.0             47260.0   725.000000
                                  Washington, DC      Washington-Arlington-Alexandria, DC-VA-MD-WV 395209.0             47900.0   619.666667
                                  Winchester, VA      Winchester, VA-WV                            395232.0             49020.0   840.000000

                                                                                                                                  CountyRegionID_Zillow  \
Year Month     State    StateFIPS MetroName_Zillow    CBSAName                                     MetroRegionID_Zillow CBSACode
1990 April     Maryland 24.0      Baltimore, MD       Baltimore-Columbia-Towson, MD                394358.0             12580.0             3236.000000
               Missouri 29.0      St. Louis, MO       St. Louis, MO-IL                             395121.0             41180.0             3269.000000
               Nevada   32.0      Carson City, NV     Carson City, NV                              394444.0             16180.0             3087.000000
               Virginia 51.0      Big Stone Gap, VA   Big Stone Gap, VA                            753866.0             13720.0             3114.000000
                                  Blacksburg, VA      Blacksburg-Christiansburg-Radford, VA        394392.0             13980.0             3182.000000
                                  Charlottesville, VA Charlottesville, VA                          394459.0             16820.0             3288.000000
                                  Danville, VA        Danville, VA                                 394518.0             19260.0             3205.000000
                                  Harrisonburg, VA    Harrisonburg, VA                             394668.0             25500.0             3273.000000
                                  Kingsport, TN       Kingsport-Bristol-Bristol, TN-VA             394747.0             28700.0             1560.000000
                                  Lynchburg, VA       Lynchburg, VA                                394811.0             31340.0             3243.000000

In [14]:
first_grouped_data = unemployment_monthly_data.groupby(column_list).mean()

In [15]:
first_grouped_data = first_grouped_data.reset_index()

In [16]:
first_grouped_data

,Year,Month,State,StateFIPS,MetroName_Zillow,CBSAName,MetroRegionID_Zillow,CBSACode,Unemployment Rate,CountyFIPS,CountyRegionID_Zillow,FIPS
0,1990,April,Maryland,24.0,"Baltimore, MD","Baltimore-Columbia-Towson, MD",394358.0,12580.0,6.500000,510.000000,3236.000000,24510.000000
1,1990,April,Missouri,29.0,"St. Louis, MO","St. Louis, MO-IL",395121.0,41180.0,8.000000,510.000000,3269.000000,29510.000000
2,1990,April,Nevada,32.0,"Carson City, NV","Carson City, NV",394444.0,16180.0,5.500000,510.000000,3087.000000,32510.000000
3,1990,April,Virginia,51.0,"Big Stone Gap, VA","Big Stone Gap, VA",753866.0,13720.0,9.900000,720.000000,3114.000000,51720.000000
4,1990,April,Virginia,51.0,"Blacksburg, VA","Blacksburg-Christiansburg-Radford, VA",394392.0,13980.0,9.400000,750.000000,3182.000000,51750.000000
5,1990,April,Virginia,51.0,"Charlottesville, VA","Charlottesville, VA",394459.0,16820.0,1.700000,540.000000,3288.000000,51540.000000
6,1990,April,Virginia,51.0,"Danville, VA","Danville, VA",394518.0,19260.0,9.400000,590.000000,3205.000000,51590.000000
7,1990,April,Virginia,51.0,"Harrisonburg, VA","Harrisonburg, VA",394668.0,25500.0,5.000000,660.000000,3273.000000,51660.000000
8,1990,April,Virginia,51.0,"Kingsport, TN","Kingsport-Bristol-Bristol, TN-VA",394747.0,28700.0,6.600000,520.000000,1560.000000,51520.000000
9,1990,April,Virginia,51.0,"Lynchburg, VA","Lynchburg, VA",394811.0,31340.0,5.200000,680.000000,3243.000000,51680.000000
10,1990,April,Virginia,51.0,"Martinsville, VA","Martinsville, VA",394836.0,32300.0,6.200000,690.000000,3276.000000,51690.000000
11,1990,April,Virginia,51.0,"Richmond, VA","Richmond, VA",395022.0,40060.0,5.200000,682.500000,3244.500000,51682.500000
12,1990,April,Virginia,51.0,"Roanoke, VA","Roanoke, VA",395028.0,40220.0,3.350000,772.500000,1943.500000,51772.500000
13,1990,April,Virginia,51.0,"Staunton, VA","Staunton-Waynesboro, VA",395128.0,44420.0,3.350000,805.000000,3246.000000,51805.000000
14,1990,April,Virginia,51.0,"Virginia Beach, VA","Virginia Beach-Norfolk-Newport News, VA-NC",395194.0,47260.0,4.811111,725.000000,3233.666667,51725.000000
15,1990,April,Virginia,51.0,"Washington, DC","Washington-Arlington-Alexandria, DC-VA-MD-WV",395209.0,47900.0,2.166667,619.666667,3244.166667,51619.666667
16,1990,April,Virginia,51.0,"Winchester, VA","Winchester, VA-WV",395232.0,49020.0,5.500000,840.000000,3263.000000,51840.000000
17,1990,August,Maryland,24.0,"Baltimore, MD","Baltimore-Columbia-Towson, MD",394358.0,12580.0,8.200000,510.000000,3236.000000,24510.000000
18,1990,August,Missouri,29.0,"St. Louis, MO","St. Louis, MO-IL",395121.0,41180.0,9.300000,510.000000,3269.000000,29510.000000
19,1990,August,Nevada,32.0,"Carson City, NV","Carson City, NV",394444.0,16180.0,4.800000,510.000000,3087.000000,32510.000000
20,1990,August,Virginia,51.0,"Big Stone Gap, VA","Big Stone Gap, VA",753866.0,13720.0,8.700000,720.000000,3114.000000,51720.000000
21,1990,August,Virginia,51.0,"Blacksburg, VA","Blacksburg-Christiansburg-Radford, VA",394392.0,13980.0,13.300000,750.000000,3182.000000,51750.000000
22,1990,August,Virginia,51.0,"Charlottesville, VA","Charlottesville, VA",394459.0,16820.0,3.200000,540.000000,3288.000000,51540.000000
23,1990,August,Virginia,51.0,"Danville, VA","Danville, VA",394518.0,19260.0,10.300000,590.000000,3205.000000,51590.000000
24,1990,August,Virginia,51.0,"Harrisonburg, VA","Harrisonburg, VA",394668.0,25500.0,6.600000,660.000000,3273.000000,51660.000000
25,1990,August,Virginia,51.0,"Kingsport, TN","Kingsport-Bristol-Bristol, TN-VA",394747.0,28700.0,8.700000,520.000000,1560.000000,51520.000000
26,1990,August,Virginia,51.0,"Lynchburg, VA","Lynchburg, VA",394811.0,31340.0,6.300000,680.000000,3243.000000,51680.000000
27,1990,August,Virginia,51.0,"Martinsville, VA","Martinsville, VA",394836.0,32300.0,6.600000,690.000000,3276.000000,51690.000000
28,1990,August,Virginia,51.0,"Richmond, VA","Richmond, VA",395022.0,40060.0,6.300000,682.500000,3244.500000,51682.500000
29,1990,August,Virginia,51.0,"Roanoke, VA","Roanoke, VA",395028.0,40220.0,3.900000,772.500000,1943.500000,51772.500000
...,...,...,...,...,...,...,...,...,...,...,...,...
5142,2016,October,Virginia,51.0,"Blacksburg, VA","Blacksburg-Christiansburg-Radford, VA",394392.0,13980.0,5.400000,750.000000,3182.000000,51750.000000
5143,2016,October,Virginia,51.0,"Charlottesville, VA","Charlottesville, VA",394459.0,16820.0,3.400000,540.000000,3288.000000,51540.000000
5144,2016,October,Virginia,51.0,"Danville, VA","Danville, VA",394518.0,19260.0,5.700000,590.000000,3205.000000,51590.000000
5145,2016,October,Virginia,51.0,"Harrisonburg, VA","Harrisonburg, VA",394668.0,25500.0,5.000000,660.000000,3273.000000,51660.000000
5146,2016,October,Virginia,51.0,"Kingsport, TN","Kingsport-Bristol-Bristol, TN-VA",394747.0,28700.0,5.200000,520.000000,1560.000000,51520.000000
5147,2016,October,Virginia,51.0,"Lynchburg, VA","Lynchburg, VA",394811.0,31340.0,5.200000,680.000000,3243.000000,51680.000000
5148,2016,October,Virginia,51.0,"Martinsville, VA","Martinsville, VA",394836.0,32300.0,6.800000,690.000000,3276.000000,51690.000000
5149,2016,October,Virginia,51.0,"Richmond, VA","Richmond, VA",395022.0,40060.0,5.525000,682.500000,3244.500000,51682.500000
5150,2016,October,Virginia,51.0,"Roanoke, VA","Roanoke, VA",395028.0,40220.0,4.150000,772.500000,1943.500000,51772.500000
5151,2016,October,Virginia,51.0,"Staunton, VA","Staunton-Waynesboro, VA",395128.0,44420.0,4.350000,805.000000,3246.000000,51805.000000
5152,2016,October,Virginia,51.0,"Virginia Beach, VA","Virginia Beach-Norfolk-Newport News, VA-NC",395194.0,47260.0,4.922222,725.000000,3233.666667,51725.000000
5153,2016,October,Virginia,51.0,"Washington, DC","Washington-Arlington-Alexandria, DC-VA-MD-WV",395209.0,47900.0,3.500000,619.666667,3244.166667,51619.666667
5154,2016,October,Virginia,51.0,"Winchester, VA","Winchester, VA-WV",395232.0,49020.0,4.000000,840.000000,3263.000000,51840.000000
5155,2016,September,Maryland,24.0,"Baltimore, MD","Baltimore-Columbia-Towson, MD",394358.0,12580.0,5.800000,510.000000,3236.000000,24510.000000
5156,2016,September,Missouri,29.0,"St. Louis, MO","St. Louis, MO-IL",395121.0,41180.0,5.700000,510.000000,3269.000000,29510.000000
5157,2016,September,Nevada,32.0,"Carson City, NV","Carson City, NV",394444.0,16180.0,5.600000,510.000000,3087.000000,32510.000000
5158,2016,September,Virginia,51.0,"Big Stone Gap, VA","Big Stone Gap, VA",753866.0,13720.0,6.700000,720.000000,3114.000000,51720.000000
5159,2016,September,Virginia,51.0,"Blacksburg, VA","Blacksburg-Christiansburg-Radford, VA",394392.0,13980.0,5.200000,750.000000,3182.000000,51750.000000
5160,2016,September,Virginia,51.0,"Charlottesville, VA","Charlottesville, VA",394459.0,16820.0,3.300000,540.000000,3288.000000,51540.000000
5161,2016,September,Virginia,51.0,"Danville, VA","Danville, VA",394518.0,19260.0,5.800000,590.000000,3205.000000,51590.000000
5162,2016,September,Virginia,51.0,"Harrisonburg, VA","Harrisonburg, VA",394668.0,25500.0,4.800000,660.000000,3273.000000,51660.000000
5163,2016,September,Virginia,51.0,"Kingsport, TN","Kingsport-Bristol-Bristol, TN-VA",394747.0,28700.0,5.400000,520.000000,1560.000000,51520.000000
5164,2016,September,Virginia,51.0,"Lynchburg, VA","Lynchburg, VA",394811.0,31340.0,5.200000,680.000000,3243.000000,51680.000000
5165,2016,September,Virginia,51.0,"Martinsville, VA","Martinsville, VA",394836.0,32300.0,6.800000,690.000000,3276.000000,51690.000000
5166,2016,September,Virginia,51.0,"Richmond, VA","Richmond, VA",395022.0,40060.0,5.625000,682.500000,3244.500000,51682.500000
5167,2016,September,Virginia,51.0,"Roanoke, VA","Roanoke, VA",395028.0,40220.0,4.100000,772.500000,1943.500000,51772.500000
5168,2016,September,Virginia,51.0,"Staunton, VA","Staunton-Waynesboro, VA",395128.0,44420.0,4.150000,805.000000,3246.000000,51805.000000
5169,2016,September,Virginia,51.0,"Virginia Beach, VA","Virginia Beach-Norfolk-Newport News, VA-NC",395194.0,47260.0,4.888889,725.000000,3233.666667,51725.000000
5170,2016,September,Virginia,51.0,"Washington, DC","Washington-Arlington-Alexandria, DC-VA-MD-WV",395209.0,47900.0,3.416667,619.666667,3244.166667,51619.666667
5171,2016,September,Virginia,51.0,"Winchester, VA","Winchester, VA-WV",395232.0,49020.0,3.900000,840.000000,3263.000000,51840.000000

In [17]:
county_time_series = pd.read_csv(path_3)

In [18]:
county_time_series

,Date,RegionName,DaysOnZillow_AllHomes,InventorySeasonallyAdjusted_AllHomes,InventoryRaw_AllHomes,MedianListingPricePerSqft_1Bedroom,MedianListingPricePerSqft_2Bedroom,MedianListingPricePerSqft_3Bedroom,MedianListingPricePerSqft_4Bedroom,MedianListingPricePerSqft_5BedroomOrMore,...,ZHVI_BottomTier,ZHVI_CondoCoop,ZHVI_MiddleTier,ZHVI_SingleFamilyResidence,ZHVI_TopTier,ZRI_AllHomes,ZRI_AllHomesPlusMultifamily,ZriPerSqft_AllHomes,Zri_MultiFamilyResidenceRental,Zri_SingleFamilyResidenceRental
0,1996-04-30,10001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,65600.0,NaN,85700.0,86000.0,129700.0,NaN,NaN,NaN,NaN,NaN
1,1996-04-30,10003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,81900.0,NaN,116800.0,116900.0,181400.0,NaN,NaN,NaN,NaN,NaN
2,1996-04-30,1003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,70600.0,NaN,110600.0,106800.0,192300.0,NaN,NaN,NaN,NaN,NaN
3,1996-04-30,1009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,70000.0,70000.0,123500.0,NaN,NaN,NaN,NaN,NaN
4,1996-04-30,1017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1996-04-30,1051,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,89400.0,NaN,NaN,NaN,NaN,NaN,NaN
6,1996-04-30,1055,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,71300.0,71300.0,126700.0,NaN,NaN,NaN,NaN,NaN
7,1996-04-30,1069,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,56400.0,NaN,92600.0,92600.0,172900.0,NaN,NaN,NaN,NaN,NaN
8,1996-04-30,1073,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,74700.0,72700.0,72700.0,149900.0,NaN,NaN,NaN,NaN,NaN
9,1996-04-30,1077,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,1996-04-30,1081,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,68100.0,85800.0,104800.0,105200.0,182400.0,NaN,NaN,NaN,NaN,NaN
11,1996-04-30,1097,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,38400.0,76600.0,61100.0,60800.0,107100.0,NaN,NaN,NaN,NaN,NaN
12,1996-04-30,1099,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,62600.0,62600.0,107500.0,NaN,NaN,NaN,NaN,NaN
13,1996-04-30,1101,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,49200.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,1996-04-30,1113,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,76000.0,NaN,106500.0,106500.0,149900.0,NaN,NaN,NaN,NaN,NaN
15,1996-04-30,1115,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,81900.0,90300.0,90600.0,145900.0,NaN,NaN,NaN,NaN,NaN
16,1996-04-30,1117,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,86900.0,95900.0,130000.0,132600.0,212300.0,NaN,NaN,NaN,NaN,NaN
17,1996-04-30,1125,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,61500.0,97200.0,101800.0,102200.0,160700.0,NaN,NaN,NaN,NaN,NaN
18,1996-04-30,12001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,49100.0,58300.0,80900.0,86500.0,142500.0,NaN,NaN,NaN,NaN,NaN
19,1996-04-30,12005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,55800.0,102500.0,86400.0,83300.0,141700.0,NaN,NaN,NaN,NaN,NaN
20,1996-04-30,12009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,49400.0,60100.0,78700.0,82000.0,117100.0,NaN,NaN,NaN,NaN,NaN
21,1996-04-30,12011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,49000.0,57900.0,86100.0,115300.0,160100.0,NaN,NaN,NaN,NaN,NaN
22,1996-04-30,12015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,51800.0,70500.0,82900.0,85800.0,139100.0,NaN,NaN,NaN,NaN,NaN
23,1996-04-30,12019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,66100.0,66500.0,94300.0,96100.0,148400.0,NaN,NaN,NaN,NaN,NaN
24,1996-04-30,12021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,77300.0,120400.0,134100.0,154300.0,NaN,NaN,NaN,NaN,NaN,NaN
25,1996-04-30,12023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,39200.0,NaN,69600.0,69600.0,110500.0,NaN,NaN,NaN,NaN,NaN
26,1996-04-30,12027,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,1996-04-30,12031,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,49300.0,68300.0,79100.0,80600.0,127000.0,NaN,NaN,NaN,NaN,NaN
28,1996-04-30,12033,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,45500.0,NaN,78200.0,75600.0,129900.0,NaN,NaN,NaN,NaN,NaN
29,1996-04-30,12035,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,132900.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
518761,2017-12-31,8077,NaN,621.0,602.0,NaN,156.175595,151.731515,149.769585,151.098098,...,156600.0,133600.0,214300.0,218100.0,323500.0,1201.0,1194.0,0.852,908.0,1205.0
518762,2017-12-31,8079,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
518763,2017-12-31,8081,NaN,NaN,NaN,NaN,NaN,99.568587,NaN,NaN,...,106300.0,NaN,159000.0,159000.0,224900.0,1242.0,1252.0,0.810,1284.0,1250.0
518764,2017-12-31,8083,NaN,243.0,220.0,NaN,165.734499,166.874480,NaN,NaN,...,137700.0,NaN,206500.0,206500.0,334600.0,1371.0,1350.0,0.978,NaN,1351.0
518765,2017-12-31,8085,NaN,256.0,222.0,NaN,158.274143,157.750207,151.762141,NaN,...,166000.0,160400.0,230300.0,231400.0,369600.0,1272.0,1262.0,0.788,1029.0,1264.0
518766,2017-12-31,8087,NaN,132.0,138.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
518767,2017-12-31,8089,NaN,38.0,42.0,NaN,NaN,NaN,NaN,NaN,...,51200.0,NaN,74200.0,74200.0,144200.0,NaN,NaN,NaN,NaN,NaN
518768,2017-12-31,8091,NaN,NaN,NaN,NaN,NaN,218.550955,NaN,NaN,...,256900.0,NaN,374200.0,410000.0,600700.0,1799.0,1742.0,1.174,1297.0,1867.0
518769,2017-12-31,8093,NaN,252.0,220.0,NaN,252.333333,228.298611,NaN,NaN,...,187800.0,NaN,281900.0,281900.0,417300.0,1610.0,1601.0,1.154,NaN,1602.0
518770,2017-12-31,8097,NaN,515.0,489.0,830.169089,753.825975,815.126050,966.711825,1231.527094,...,462000.0,705700.0,1189400.0,2788700.0,4639500.0,NaN,NaN,NaN,NaN,NaN
518771,2017-12-31,8099,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1048.0,1056.0,NaN,NaN,1057.0
518772,2017-12-31,8101,NaN,434.0,430.0,NaN,121.590909,150.896861,171.519608,NaN,...,81400.0,103400.0,146700.0,147500.0,243700.0,1174.0,1152.0,0.942,884.0,1175.0
518773,2017-12-31,8103,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1382.0,1383.0,0.644,NaN,1386.0
518774,2017-12-31,8105,NaN,189.0,182.0,NaN,147.058824,142.195767,137.500000,NaN,...,83000.0,NaN,139900.0,139900.0,256100.0,1180.0,1196.0,0.824,NaN,1196.0
518775,2017-12-31,8107,NaN,465.0,411.0,NaN,317.264574,304.166667,372.769059,418.649353,...,239900.0,341200.0,423300.0,556000.0,785600.0,2132.0,2053.0,1.792,1798.0,3001.0
518776,2017-12-31,8109,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
518777,2017-12-31,8111,NaN,41.0,40.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
518778,2017-12-31,8113,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,285200.0,557700.0,NaN,829400.0,1827000.0,2292.0,NaN,NaN,2116.0,NaN
518779,2017-12-31,8117,NaN,NaN,NaN,538.805970,450.968500,418.794160,395.638525,439.591605,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
518780,2017-12-31,8119,NaN,172.0,144.0,NaN,NaN,208.896831,220.608532,NaN,...,157600.0,NaN,263900.0,264900.0,407500.0,1550.0,1544.0,0.880,NaN,1548.0
518781,2017-12-31,8123,NaN,1118.0,1038.0,NaN,203.598485,178.208556,167.959939,177.850394,...,209000.0,228900.0,289300.0,294500.0,417700.0,1628.0,1606.0,0.996,1357.0,1636.0
518782,2017-12-31,8125,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
518783,2017-12-31,9001,NaN,6085.0,5150.0,225.965489,240.663900,242.015968,239.105829,353.083804,...,218300.0,243600.0,398900.0,454900.0,859100.0,2388.0,2299.0,1.490,1824.0,2505.0
518784,2017-12-31,9003,NaN,3805.0,3476.0,118.613139,132.242340,149.536049,147.552448,115.845886,...,139200.0,142500.0,213600.0,226700.0,344800.0,1670.0,1596.0,1.154,1289.0,1727.0
518785,2017-12-31,9005,NaN,1751.0,1606.0,149.550158,133.285714,144.523796,148.828677,149.550484,...,142200.0,120700.0,235900.0,248000.0,388100.0,1552.0,1495.0,1.042,1191.0,1640.0
518786,2017-12-31,9007,NaN,1233.0,1128.0,NaN,150.265252,162.745814,152.768512,142.396246,...,172500.0,142900.0,259700.0,272400.0,381000.0,1620.0,1583.0,1.070,1302.0,1660.0
518787,2017-12-31,9009,NaN,4153.0,3710.0,145.474138,142.480588,155.308393,153.251934,108.097484,...,131700.0,132700.0,220000.0,238800.0,360200.0,1669.0,1593.0,1.154,1294.0,1729.0
518788,2017-12-31,9011,NaN,1651.0,1514.0,143.055556,137.813212,149.931507,138.903723,102.903196,...,157100.0,137700.0,224400.0,231500.0,361100.0,1566.0,1521.0,1.078,1150.0,1591.0
518789,2017-12-31,9013,NaN,736.0,655.0,NaN,140.014368,150.625992,136.361382,98.393826,...,157500.0,118700.0,220000.0,226400.0,327100.0,1709.0,1668.0,1.082,1311.0,1755.0
518790,2017-12-31,9015,NaN,538.0,490.0,NaN,133.359498,138.411079,113.813421,71.193866,...,143200.0,142700.0,191300.0,192700.0,272900.0,1325.0,1316.0,0.922,1124.0,1329.0

In [20]:
metro_data = pd.read_csv('datasets/metro_data.csv')

In [21]:
metro_data = metro_data.drop('Unnamed: 0', axis=1)

In [22]:
metro_data

,Date,RegionName,AgeOfInventory,DaysOnZillow_AllHomes,InventorySeasonallyAdjusted_AllHomes,InventoryRaw_AllHomes,InventorySeasonallyAdjusted_BottomTier,InventorySeasonallyAdjusted_MiddleTier,InventorySeasonallyAdjusted_TopTier,MedianListingPricePerSqft_1Bedroom,...,ZHVI_CondoCoop,ZHVI_MiddleTier,ZHVI_SingleFamilyResidence,ZHVI_TopTier,ZRI_AllHomes,ZRI_AllHomesPlusMultifamily,ZriPerSqft_AllHomes,Zri_MultiFamilyResidenceRental,Zri_SingleFamilyResidenceRental,MetroName
0,1996-04-30,10180,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Abilene, TX"
1,1996-04-30,10220,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,28600.0,28600.0,NaN,NaN,NaN,NaN,NaN,NaN,"Ada, OK"
2,1996-04-30,10300,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,78500.0,78600.0,124800.0,NaN,NaN,NaN,NaN,NaN,"Adrian, MI"
3,1996-04-30,10420,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,109000.0,95700.0,94400.0,169400.0,NaN,NaN,NaN,NaN,NaN,"Akron, OH"
4,1996-04-30,10500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,67600.0,67500.0,112400.0,NaN,NaN,NaN,NaN,NaN,"Albany, GA"
5,1996-04-30,10540,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,84800.0,102900.0,102800.0,143000.0,NaN,NaN,NaN,NaN,NaN,"Albany, OR"
6,1996-04-30,10580,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,65400.0,95200.0,95500.0,146800.0,NaN,NaN,NaN,NaN,NaN,"Albany, NY"
7,1996-04-30,10620,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,70000.0,70000.0,121600.0,NaN,NaN,NaN,NaN,NaN,"Albemarle, NC"
8,1996-04-30,10740,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,93300.0,116000.0,116400.0,169900.0,NaN,NaN,NaN,NaN,NaN,"Albuquerque, NM"
9,1996-04-30,10780,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,59800.0,59800.0,107900.0,NaN,NaN,NaN,NaN,NaN,"Alexandria, LA"
10,1996-04-30,10900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,100600.0,108100.0,108400.0,166600.0,NaN,NaN,NaN,NaN,NaN,"Allentown, PA"
11,1996-04-30,11020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,55000.0,55000.0,NaN,NaN,NaN,NaN,NaN,NaN,"Altoona, PA"
12,1996-04-30,11060,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,42400.0,42400.0,NaN,NaN,NaN,NaN,NaN,NaN,"Altus, OK"
13,1996-04-30,11100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,52400.0,64400.0,64500.0,NaN,NaN,NaN,NaN,NaN,NaN,"Amarillo, TX"
14,1996-04-30,11140,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Americus, GA"
15,1996-04-30,11180,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Ames, IA"
16,1996-04-30,11220,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,55800.0,55800.0,NaN,NaN,NaN,NaN,NaN,NaN,"Amsterdam, NY"
17,1996-04-30,11420,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,88500.0,88500.0,NaN,NaN,NaN,NaN,NaN,NaN,"Angola, IN"
18,1996-04-30,11460,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,125300.0,128000.0,128600.0,218000.0,NaN,NaN,NaN,NaN,NaN,"Ann Arbor, MI"
19,1996-04-30,11540,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,81500.0,88900.0,88900.0,134300.0,NaN,NaN,NaN,NaN,NaN,"Appleton, WI"
20,1996-04-30,11580,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Arcadia, FL"
21,1996-04-30,11620,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,43000.0,43000.0,85300.0,NaN,NaN,NaN,NaN,NaN,"Ardmore, OK"
22,1996-04-30,11700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,98500.0,89600.0,88100.0,151400.0,NaN,NaN,NaN,NaN,NaN,"Asheville, NC"
23,1996-04-30,11740,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,80900.0,80600.0,121000.0,NaN,NaN,NaN,NaN,NaN,"Ashland, OH"
24,1996-04-30,11780,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,67900.0,63500.0,63600.0,101600.0,NaN,NaN,NaN,NaN,NaN,"Ashtabula, OH"
25,1996-04-30,11820,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Astoria, OR"
26,1996-04-30,11940,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,65300.0,65400.0,116700.0,NaN,NaN,NaN,NaN,NaN,"Athens, TN"
27,1996-04-30,11980,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Athens, TX"
28,1996-04-30,12020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,66700.0,86300.0,87100.0,154400.0,NaN,NaN,NaN,NaN,NaN,"Athens, GA"
29,1996-04-30,12060,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,92900.0,106700.0,108000.0,182300.0,NaN,NaN,NaN,NaN,NaN,"Atlanta, GA"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210891,2017-12-31,48260,NaN,NaN,476.0,467.0,NaN,NaN,NaN,NaN,...,NaN,85200.0,85100.0,132400.0,738.0,735.0,0.604,703.0,736.0,"Weirton, OH"
210892,2017-12-31,48300,134.0,NaN,607.0,546.0,NaN,115.0,245.0,NaN,...,236500.0,291900.0,300000.0,461300.0,1549.0,1539.0,1.164,1377.0,1558.0,"Wenatchee, WA"
210893,2017-12-31,48460,155.0,NaN,378.0,374.0,114.0,84.0,177.0,NaN,...,NaN,117000.0,117000.0,189800.0,NaN,NaN,NaN,NaN,NaN,"West Plains, MO"
210894,2017-12-31,48540,NaN,NaN,424.0,415.0,102.0,NaN,217.0,NaN,...,NaN,91900.0,92000.0,158400.0,872.0,859.0,0.710,767.0,870.0,"Wheeling, OH"
210895,2017-12-31,48580,137.0,NaN,861.0,745.0,177.0,231.0,453.0,136.765148,...,NaN,197100.0,191900.0,354200.0,1412.0,1401.0,0.894,1493.0,1391.0,"Whitewater, WI"
210896,2017-12-31,48620,76.0,NaN,2170.0,2116.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,976.0,954.0,0.740,747.0,975.0,"Wichita, KS"
210897,2017-12-31,48660,NaN,NaN,577.0,514.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,172500.0,904.0,895.0,0.642,601.0,902.0,"Wichita Falls, TX"
210898,2017-12-31,48700,105.0,NaN,389.0,372.0,104.0,116.0,169.0,NaN,...,NaN,146800.0,146800.0,213900.0,987.0,966.0,0.688,796.0,982.0,"Williamsport, PA"
210899,2017-12-31,48780,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,288300.0,NaN,NaN,NaN,NaN,NaN,"Williston, ND"
210900,2017-12-31,48820,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,163300.0,163400.0,NaN,1239.0,1231.0,0.756,1147.0,1233.0,"Willmar, MN"
210901,2017-12-31,48900,112.0,NaN,2142.0,2016.0,315.0,665.0,1164.0,367.521368,...,174600.0,217800.0,221400.0,394700.0,1390.0,1352.0,0.896,1139.0,1394.0,"Wilmington, NC"
210902,2017-12-31,48940,NaN,NaN,106.0,100.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Wilmington, OH"
210903,2017-12-31,48980,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,124900.0,124800.0,204400.0,NaN,NaN,NaN,NaN,NaN,"Wilson, NC"
210904,2017-12-31,49020,94.0,NaN,760.0,722.0,200.0,210.0,349.0,NaN,...,NaN,210000.0,210000.0,337000.0,1335.0,1328.0,0.884,1039.0,1330.0,"Winchester, VA"
210905,2017-12-31,49080,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,193300.0,193600.0,302500.0,1293.0,1264.0,0.888,1185.0,1277.0,"Winnemucca, NV"
210906,2017-12-31,49100,NaN,NaN,141.0,130.0,44.0,50.0,50.0,NaN,...,NaN,143200.0,143200.0,228700.0,NaN,NaN,NaN,NaN,NaN,"Winona, MN"
210907,2017-12-31,49180,95.0,NaN,2434.0,2260.0,440.0,682.0,1298.0,NaN,...,95200.0,133100.0,135000.0,227500.0,1052.0,1040.0,0.686,847.0,1058.0,"Winston-Salem, NC"
210908,2017-12-31,49220,94.0,NaN,345.0,314.0,123.0,71.0,151.0,NaN,...,NaN,120000.0,120000.0,168500.0,970.0,955.0,0.596,750.0,957.0,"Wisconsin Rapids-Marshfield, WI"
210909,2017-12-31,49260,NaN,NaN,110.0,102.0,NaN,NaN,NaN,NaN,...,NaN,117000.0,117000.0,166200.0,971.0,971.0,0.662,NaN,972.0,"Woodward, OK"
210910,2017-12-31,49300,62.0,NaN,244.0,235.0,85.0,72.0,NaN,NaN,...,126200.0,146600.0,147600.0,222100.0,1191.0,1169.0,0.820,875.0,1193.0,"Wooster, OH"
210911,2017-12-31,49340,76.0,NaN,2532.0,2250.0,733.0,742.0,1055.0,167.930368,...,185400.0,257300.0,265200.0,403300.0,1653.0,1592.0,1.126,1270.0,1672.0,"Worcester, MA"
210912,2017-12-31,49380,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1072.0,1070.0,1.042,NaN,1070.0,"Worthington, MN"
210913,2017-12-31,49420,88.0,NaN,524.0,463.0,NaN,99.0,267.0,NaN,...,188600.0,189200.0,189300.0,289000.0,1181.0,1155.0,0.856,1014.0,1179.0,"Yakima, WA"
210914,2017-12-31,49460,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,163700.0,163700.0,NaN,1187.0,1174.0,NaN,NaN,1174.0,"Yankton, SD"
210915,2017-12-31,49620,NaN,NaN,1791.0,1738.0,524.0,454.0,817.0,NaN,...,121100.0,167100.0,174300.0,258500.0,1291.0,1270.0,0.870,1008.0,1299.0,"York, PA"
210916,2017-12-31,49660,NaN,NaN,2479.0,2396.0,709.0,659.0,1111.0,NaN,...,119400.0,86900.0,85900.0,162800.0,848.0,838.0,0.622,815.0,840.0,"Youngstown, OH"
210917,2017-12-31,49700,60.0,NaN,284.0,266.0,NaN,NaN,115.0,NaN,...,NaN,272600.0,274100.0,370000.0,1423.0,1410.0,0.888,1161.0,1428.0,"Yuba City, CA"
210918,2017-12-31,49740,64.0,NaN,793.0,855.0,132.0,236.0,426.0,NaN,...,114400.0,137500.0,140700.0,229100.0,904.0,903.0,0.690,846.0,912.0,"Yuma, AZ"
210919,2017-12-31,49780,NaN,NaN,323.0,292.0,103.0,68.0,154.0,NaN,...,126900.0,114100.0,113500.0,172000.0,937.0,921.0,0.710,843.0,922.0,"Zanesville, OH"
210920,2017-12-31,49820,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,94900.0,94900.0,167600.0,NaN,NaN,NaN,NaN,NaN,"Zapata, TX"

In [23]:
new_metro_data = metro_data.rename(columns={'RegionName': 'CBSACode'})

In [24]:
new_metro_data = new_metro_data[['Date', 
'CBSACode',
'ZHVIPerSqft_AllHomes',
 'ZHVI_1bedroom',
 'ZHVI_2bedroom',
 'ZHVI_3bedroom',
 'ZHVI_4bedroom',
 'ZHVI_5BedroomOrMore',
 'ZHVI_AllHomes',
 'ZHVI_BottomTier',
 'ZHVI_CondoCoop',
 'ZHVI_MiddleTier',
 'ZHVI_SingleFamilyResidence',
 'ZHVI_TopTier']]

In [25]:
new_metro_data

,Date,CBSACode,ZHVIPerSqft_AllHomes,ZHVI_1bedroom,ZHVI_2bedroom,ZHVI_3bedroom,ZHVI_4bedroom,ZHVI_5BedroomOrMore,ZHVI_AllHomes,ZHVI_BottomTier,ZHVI_CondoCoop,ZHVI_MiddleTier,ZHVI_SingleFamilyResidence,ZHVI_TopTier
0,1996-04-30,10180,NaN,NaN,NaN,66600.0,113200.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1996-04-30,10220,21.0,NaN,19700.0,NaN,NaN,NaN,28600.0,NaN,NaN,28600.0,28600.0,NaN
2,1996-04-30,10300,61.0,71600.0,71000.0,89000.0,96300.0,111600.0,78500.0,53000.0,NaN,78500.0,78600.0,124800.0
3,1996-04-30,10420,66.0,54000.0,67300.0,92300.0,164100.0,160000.0,95700.0,54900.0,109000.0,95700.0,94400.0,169400.0
4,1996-04-30,10500,41.0,NaN,NaN,65000.0,116100.0,194500.0,67600.0,NaN,NaN,67600.0,67500.0,112400.0
5,1996-04-30,10540,75.0,64200.0,78600.0,106700.0,134700.0,143200.0,102900.0,77500.0,84800.0,102900.0,102800.0,143000.0
6,1996-04-30,10580,65.0,62100.0,75900.0,92100.0,126900.0,133500.0,95200.0,69400.0,65400.0,95200.0,95500.0,146800.0
7,1996-04-30,10620,44.0,NaN,NaN,77200.0,117000.0,144700.0,70000.0,NaN,NaN,70000.0,70000.0,121600.0
8,1996-04-30,10740,64.0,85500.0,94500.0,115400.0,156000.0,195000.0,116000.0,86700.0,93300.0,116000.0,116400.0,169900.0
9,1996-04-30,10780,54.0,NaN,66700.0,89500.0,153600.0,NaN,59800.0,NaN,NaN,59800.0,59800.0,107900.0
10,1996-04-30,10900,67.0,78700.0,83600.0,98500.0,158000.0,104900.0,108100.0,70800.0,100600.0,108100.0,108400.0,166600.0
11,1996-04-30,11020,NaN,NaN,NaN,NaN,NaN,NaN,55000.0,NaN,NaN,55000.0,55000.0,NaN
12,1996-04-30,11060,NaN,NaN,NaN,50100.0,NaN,NaN,42400.0,NaN,NaN,42400.0,42400.0,NaN
13,1996-04-30,11100,41.0,NaN,NaN,68100.0,118200.0,NaN,64400.0,NaN,52400.0,64400.0,64500.0,NaN
14,1996-04-30,11140,26.0,NaN,NaN,NaN,70200.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,1996-04-30,11180,67.0,NaN,NaN,NaN,NaN,118900.0,NaN,NaN,NaN,NaN,NaN,NaN
16,1996-04-30,11220,38.0,NaN,48700.0,58500.0,60300.0,61000.0,55800.0,40200.0,NaN,55800.0,55800.0,NaN
17,1996-04-30,11420,61.0,62700.0,70000.0,89500.0,NaN,NaN,88500.0,62000.0,NaN,88500.0,88500.0,NaN
18,1996-04-30,11460,90.0,89900.0,101700.0,122100.0,182100.0,199900.0,128000.0,92200.0,125300.0,128000.0,128600.0,218000.0
19,1996-04-30,11540,56.0,NaN,63900.0,84900.0,104200.0,109700.0,88900.0,62900.0,81500.0,88900.0,88900.0,134300.0
20,1996-04-30,11580,NaN,NaN,NaN,NaN,90000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,1996-04-30,11620,NaN,NaN,NaN,NaN,94000.0,NaN,43000.0,NaN,NaN,43000.0,43000.0,85300.0
22,1996-04-30,11700,64.0,59300.0,69100.0,105500.0,150700.0,185700.0,89600.0,51600.0,98500.0,89600.0,88100.0,151400.0
23,1996-04-30,11740,54.0,58500.0,64400.0,84700.0,99700.0,107400.0,80900.0,52400.0,NaN,80900.0,80600.0,121000.0
24,1996-04-30,11780,50.0,NaN,NaN,69100.0,77300.0,NaN,63500.0,NaN,67900.0,63500.0,63600.0,101600.0
25,1996-04-30,11820,NaN,NaN,NaN,NaN,NaN,164000.0,NaN,NaN,NaN,NaN,NaN,NaN
26,1996-04-30,11940,41.0,NaN,NaN,65800.0,93400.0,NaN,65300.0,40000.0,NaN,65300.0,65400.0,116700.0
27,1996-04-30,11980,NaN,NaN,59100.0,NaN,NaN,NaN,NaN,41900.0,NaN,NaN,NaN,NaN
28,1996-04-30,12020,52.0,49400.0,61100.0,82200.0,125000.0,170300.0,86300.0,55500.0,66700.0,86300.0,87100.0,154400.0
29,1996-04-30,12060,59.0,81700.0,72700.0,95300.0,157500.0,221500.0,106700.0,69200.0,92900.0,106700.0,108000.0,182300.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210891,2017-12-31,48260,69.0,NaN,NaN,90900.0,106500.0,122000.0,85200.0,NaN,NaN,85200.0,85100.0,132400.0
210892,2017-12-31,48300,212.0,250200.0,250700.0,309700.0,370200.0,415600.0,291900.0,211700.0,236500.0,291900.0,300000.0,461300.0
210893,2017-12-31,48460,NaN,NaN,NaN,NaN,NaN,NaN,117000.0,78900.0,NaN,117000.0,117000.0,189800.0
210894,2017-12-31,48540,72.0,NaN,NaN,103900.0,134900.0,166300.0,91900.0,55300.0,NaN,91900.0,92000.0,158400.0
210895,2017-12-31,48580,114.0,NaN,140600.0,190100.0,246900.0,476900.0,197100.0,136900.0,NaN,197100.0,191900.0,354200.0
210896,2017-12-31,48620,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75900.0,NaN,NaN,NaN,NaN
210897,2017-12-31,48660,NaN,NaN,NaN,NaN,165300.0,245500.0,NaN,NaN,NaN,NaN,NaN,172500.0
210898,2017-12-31,48700,100.0,95300.0,118400.0,151800.0,176500.0,173200.0,146800.0,96400.0,NaN,146800.0,146800.0,213900.0
210899,2017-12-31,48780,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,288300.0
210900,2017-12-31,48820,101.0,NaN,NaN,NaN,232700.0,NaN,163300.0,107100.0,NaN,163300.0,163400.0,NaN
210901,2017-12-31,48900,134.0,NaN,145900.0,212500.0,368000.0,520100.0,217800.0,134700.0,174600.0,217800.0,221400.0,394700.0
210902,2017-12-31,48940,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
210903,2017-12-31,48980,75.0,NaN,79400.0,123000.0,204000.0,259200.0,124900.0,79100.0,NaN,124900.0,124800.0,204400.0
210904,2017-12-31,49020,136.0,103200.0,151400.0,204300.0,315700.0,357500.0,210000.0,137500.0,NaN,210000.0,210000.0,337000.0
210905,2017-12-31,49080,134.0,NaN,138700.0,210300.0,300000.0,NaN,193300.0,140600.0,NaN,193300.0,193600.0,302500.0
210906,2017-12-31,49100,98.0,96000.0,118300.0,146600.0,171600.0,162200.0,143200.0,113000.0,NaN,143200.0,143200.0,228700.0
210907,2017-12-31,49180,85.0,75600.0,83500.0,137500.0,226700.0,323400.0,133100.0,80900.0,95200.0,133100.0,135000.0,227500.0
210908,2017-12-31,49220,71.0,NaN,78900.0,115700.0,148600.0,NaN,120000.0,77500.0,NaN,120000.0,120000.0,168500.0
210909,2017-12-31,49260,79.0,NaN,NaN,NaN,158700.0,NaN,117000.0,NaN,NaN,117000.0,117000.0,166200.0
210910,2017-12-31,49300,101.0,95600.0,117400.0,147500.0,183700.0,228100.0,146600.0,95900.0,126200.0,146600.0,147600.0,222100.0
210911,2017-12-31,49340,169.0,151400.0,204200.0,256500.0,374000.0,371200.0,257300.0,176200.0,185400.0,257300.0,265200.0,403300.0
210912,2017-12-31,49380,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
210913,2017-12-31,49420,138.0,107300.0,142100.0,205400.0,240300.0,274300.0,189200.0,129400.0,188600.0,189200.0,189300.0,289000.0
210914,2017-12-31,49460,NaN,NaN,NaN,NaN,NaN,NaN,163700.0,132500.0,NaN,163700.0,163700.0,NaN
210915,2017-12-31,49620,114.0,114100.0,133500.0,165100.0,247400.0,143300.0,167100.0,119300.0,121100.0,167100.0,174300.0,258500.0
210916,2017-12-31,49660,64.0,49100.0,55300.0,84200.0,133400.0,134700.0,86900.0,45800.0,119400.0,86900.0,85900.0,162800.0
210917,2017-12-31,49700,162.0,173800.0,177400.0,259500.0,309100.0,367600.0,272600.0,191400.0,NaN,272600.0,274100.0,370000.0
210918,2017-12-31,49740,102.0,NaN,117000.0,149700.0,213500.0,294800.0,137500.0,106200.0,114400.0,137500.0,140700.0,229100.0
210919,2017-12-31,49780,83.0,78900.0,79300.0,122700.0,148300.0,183700.0,114100.0,69000.0,126900.0,114100.0,113500.0,172000.0
210920,2017-12-31,49820,73.0,NaN,NaN,NaN,NaN,NaN,94900.0,63200.0,NaN,94900.0,94900.0,167600.0

In [26]:
from datetime import datetime

In [27]:
new_metro_data['Date'] = pd.to_datetime(new_metro_data['Date'])

In [28]:
new_metro_data['Year'], new_metro_data['Month'] = new_metro_data['Date'].dt.year, new_metro_data['Date'].dt.month

In [29]:
new_metro_data

,Date,CBSACode,ZHVIPerSqft_AllHomes,ZHVI_1bedroom,ZHVI_2bedroom,ZHVI_3bedroom,ZHVI_4bedroom,ZHVI_5BedroomOrMore,ZHVI_AllHomes,ZHVI_BottomTier,ZHVI_CondoCoop,ZHVI_MiddleTier,ZHVI_SingleFamilyResidence,ZHVI_TopTier,Year,Month
0,1996-04-30,10180,NaN,NaN,NaN,66600.0,113200.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1996,4
1,1996-04-30,10220,21.0,NaN,19700.0,NaN,NaN,NaN,28600.0,NaN,NaN,28600.0,28600.0,NaN,1996,4
2,1996-04-30,10300,61.0,71600.0,71000.0,89000.0,96300.0,111600.0,78500.0,53000.0,NaN,78500.0,78600.0,124800.0,1996,4
3,1996-04-30,10420,66.0,54000.0,67300.0,92300.0,164100.0,160000.0,95700.0,54900.0,109000.0,95700.0,94400.0,169400.0,1996,4
4,1996-04-30,10500,41.0,NaN,NaN,65000.0,116100.0,194500.0,67600.0,NaN,NaN,67600.0,67500.0,112400.0,1996,4
5,1996-04-30,10540,75.0,64200.0,78600.0,106700.0,134700.0,143200.0,102900.0,77500.0,84800.0,102900.0,102800.0,143000.0,1996,4
6,1996-04-30,10580,65.0,62100.0,75900.0,92100.0,126900.0,133500.0,95200.0,69400.0,65400.0,95200.0,95500.0,146800.0,1996,4
7,1996-04-30,10620,44.0,NaN,NaN,77200.0,117000.0,144700.0,70000.0,NaN,NaN,70000.0,70000.0,121600.0,1996,4
8,1996-04-30,10740,64.0,85500.0,94500.0,115400.0,156000.0,195000.0,116000.0,86700.0,93300.0,116000.0,116400.0,169900.0,1996,4
9,1996-04-30,10780,54.0,NaN,66700.0,89500.0,153600.0,NaN,59800.0,NaN,NaN,59800.0,59800.0,107900.0,1996,4
10,1996-04-30,10900,67.0,78700.0,83600.0,98500.0,158000.0,104900.0,108100.0,70800.0,100600.0,108100.0,108400.0,166600.0,1996,4
11,1996-04-30,11020,NaN,NaN,NaN,NaN,NaN,NaN,55000.0,NaN,NaN,55000.0,55000.0,NaN,1996,4
12,1996-04-30,11060,NaN,NaN,NaN,50100.0,NaN,NaN,42400.0,NaN,NaN,42400.0,42400.0,NaN,1996,4
13,1996-04-30,11100,41.0,NaN,NaN,68100.0,118200.0,NaN,64400.0,NaN,52400.0,64400.0,64500.0,NaN,1996,4
14,1996-04-30,11140,26.0,NaN,NaN,NaN,70200.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1996,4
15,1996-04-30,11180,67.0,NaN,NaN,NaN,NaN,118900.0,NaN,NaN,NaN,NaN,NaN,NaN,1996,4
16,1996-04-30,11220,38.0,NaN,48700.0,58500.0,60300.0,61000.0,55800.0,40200.0,NaN,55800.0,55800.0,NaN,1996,4
17,1996-04-30,11420,61.0,62700.0,70000.0,89500.0,NaN,NaN,88500.0,62000.0,NaN,88500.0,88500.0,NaN,1996,4
18,1996-04-30,11460,90.0,89900.0,101700.0,122100.0,182100.0,199900.0,128000.0,92200.0,125300.0,128000.0,128600.0,218000.0,1996,4
19,1996-04-30,11540,56.0,NaN,63900.0,84900.0,104200.0,109700.0,88900.0,62900.0,81500.0,88900.0,88900.0,134300.0,1996,4
20,1996-04-30,11580,NaN,NaN,NaN,NaN,90000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1996,4
21,1996-04-30,11620,NaN,NaN,NaN,NaN,94000.0,NaN,43000.0,NaN,NaN,43000.0,43000.0,85300.0,1996,4
22,1996-04-30,11700,64.0,59300.0,69100.0,105500.0,150700.0,185700.0,89600.0,51600.0,98500.0,89600.0,88100.0,151400.0,1996,4
23,1996-04-30,11740,54.0,58500.0,64400.0,84700.0,99700.0,107400.0,80900.0,52400.0,NaN,80900.0,80600.0,121000.0,1996,4
24,1996-04-30,11780,50.0,NaN,NaN,69100.0,77300.0,NaN,63500.0,NaN,67900.0,63500.0,63600.0,101600.0,1996,4
25,1996-04-30,11820,NaN,NaN,NaN,NaN,NaN,164000.0,NaN,NaN,NaN,NaN,NaN,NaN,1996,4
26,1996-04-30,11940,41.0,NaN,NaN,65800.0,93400.0,NaN,65300.0,40000.0,NaN,65300.0,65400.0,116700.0,1996,4
27,1996-04-30,11980,NaN,NaN,59100.0,NaN,NaN,NaN,NaN,41900.0,NaN,NaN,NaN,NaN,1996,4
28,1996-04-30,12020,52.0,49400.0,61100.0,82200.0,125000.0,170300.0,86300.0,55500.0,66700.0,86300.0,87100.0,154400.0,1996,4
29,1996-04-30,12060,59.0,81700.0,72700.0,95300.0,157500.0,221500.0,106700.0,69200.0,92900.0,106700.0,108000.0,182300.0,1996,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210891,2017-12-31,48260,69.0,NaN,NaN,90900.0,106500.0,122000.0,85200.0,NaN,NaN,85200.0,85100.0,132400.0,2017,12
210892,2017-12-31,48300,212.0,250200.0,250700.0,309700.0,370200.0,415600.0,291900.0,211700.0,236500.0,291900.0,300000.0,461300.0,2017,12
210893,2017-12-31,48460,NaN,NaN,NaN,NaN,NaN,NaN,117000.0,78900.0,NaN,117000.0,117000.0,189800.0,2017,12
210894,2017-12-31,48540,72.0,NaN,NaN,103900.0,134900.0,166300.0,91900.0,55300.0,NaN,91900.0,92000.0,158400.0,2017,12
210895,2017-12-31,48580,114.0,NaN,140600.0,190100.0,246900.0,476900.0,197100.0,136900.0,NaN,197100.0,191900.0,354200.0,2017,12
210896,2017-12-31,48620,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75900.0,NaN,NaN,NaN,NaN,2017,12
210897,2017-12-31,48660,NaN,NaN,NaN,NaN,165300.0,245500.0,NaN,NaN,NaN,NaN,NaN,172500.0,2017,12
210898,2017-12-31,48700,100.0,95300.0,118400.0,151800.0,176500.0,173200.0,146800.0,96400.0,NaN,146800.0,146800.0,213900.0,2017,12
210899,2017-12-31,48780,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,288300.0,2017,12
210900,2017-12-31,48820,101.0,NaN,NaN,NaN,232700.0,NaN,163300.0,107100.0,NaN,163300.0,163400.0,NaN,2017,12
210901,2017-12-31,48900,134.0,NaN,145900.0,212500.0,368000.0,520100.0,217800.0,134700.0,174600.0,217800.0,221400.0,394700.0,2017,12
210902,2017-12-31,48940,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017,12
210903,2017-12-31,48980,75.0,NaN,79400.0,123000.0,204000.0,259200.0,124900.0,79100.0,NaN,124900.0,124800.0,204400.0,2017,12
210904,2017-12-31,49020,136.0,103200.0,151400.0,204300.0,315700.0,357500.0,210000.0,137500.0,NaN,210000.0,210000.0,337000.0,2017,12
210905,2017-12-31,49080,134.0,NaN,138700.0,210300.0,300000.0,NaN,193300.0,140600.0,NaN,193300.0,193600.0,302500.0,2017,12
210906,2017-12-31,49100,98.0,96000.0,118300.0,146600.0,171600.0,162200.0,143200.0,113000.0,NaN,143200.0,143200.0,228700.0,2017,12
210907,2017-12-31,49180,85.0,75600.0,83500.0,137500.0,226700.0,323400.0,133100.0,80900.0,95200.0,133100.0,135000.0,227500.0,2017,12
210908,2017-12-31,49220,71.0,NaN,78900.0,115700.0,148600.0,NaN,120000.0,77500.0,NaN,120000.0,120000.0,168500.0,2017,12
210909,2017-12-31,49260,79.0,NaN,NaN,NaN,158700.0,NaN,117000.0,NaN,NaN,117000.0,117000.0,166200.0,2017,12
210910,2017-12-31,49300,101.0,95600.0,117400.0,147500.0,183700.0,228100.0,146600.0,95900.0,126200.0,146600.0,147600.0,222100.0,2017,12
210911,2017-12-31,49340,169.0,151400.0,204200.0,256500.0,374000.0,371200.0,257300.0,176200.0,185400.0,257300.0,265200.0,403300.0,2017,12
210912,2017-12-31,49380,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017,12
210913,2017-12-31,49420,138.0,107300.0,142100.0,205400.0,240300.0,274300.0,189200.0,129400.0,188600.0,189200.0,189300.0,289000.0,2017,12
210914,2017-12-31,49460,NaN,NaN,NaN,NaN,NaN,NaN,163700.0,132500.0,NaN,163700.0,163700.0,NaN,2017,12
210915,2017-12-31,49620,114.0,114100.0,133500.0,165100.0,247400.0,143300.0,167100.0,119300.0,121100.0,167100.0,174300.0,258500.0,2017,12
210916,2017-12-31,49660,64.0,49100.0,55300.0,84200.0,133400.0,134700.0,86900.0,45800.0,119400.0,86900.0,85900.0,162800.0,2017,12
210917,2017-12-31,49700,162.0,173800.0,177400.0,259500.0,309100.0,367600.0,272600.0,191400.0,NaN,272600.0,274100.0,370000.0,2017,12
210918,2017-12-31,49740,102.0,NaN,117000.0,149700.0,213500.0,294800.0,137500.0,106200.0,114400.0,137500.0,140700.0,229100.0,2017,12
210919,2017-12-31,49780,83.0,78900.0,79300.0,122700.0,148300.0,183700.0,114100.0,69000.0,126900.0,114100.0,113500.0,172000.0,2017,12
210920,2017-12-31,49820,73.0,NaN,NaN,NaN,NaN,NaN,94900.0,63200.0,NaN,94900.0,94900.0,167600.0,2017,12

In [30]:
import calendar

In [31]:
new_metro_data['Month'] = new_metro_data['Month'].apply(lambda x: calendar.month_name[x])

In [32]:
new_metro_data['Year'] = new_metro_data['Year'].astype('str')

In [33]:
new_metro_data['CBSACode'] = new_metro_data['CBSACode'].astype('str')

In [34]:
new_metro_data

,Date,CBSACode,ZHVIPerSqft_AllHomes,ZHVI_1bedroom,ZHVI_2bedroom,ZHVI_3bedroom,ZHVI_4bedroom,ZHVI_5BedroomOrMore,ZHVI_AllHomes,ZHVI_BottomTier,ZHVI_CondoCoop,ZHVI_MiddleTier,ZHVI_SingleFamilyResidence,ZHVI_TopTier,Year,Month
0,1996-04-30,10180,NaN,NaN,NaN,66600.0,113200.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1996,April
1,1996-04-30,10220,21.0,NaN,19700.0,NaN,NaN,NaN,28600.0,NaN,NaN,28600.0,28600.0,NaN,1996,April
2,1996-04-30,10300,61.0,71600.0,71000.0,89000.0,96300.0,111600.0,78500.0,53000.0,NaN,78500.0,78600.0,124800.0,1996,April
3,1996-04-30,10420,66.0,54000.0,67300.0,92300.0,164100.0,160000.0,95700.0,54900.0,109000.0,95700.0,94400.0,169400.0,1996,April
4,1996-04-30,10500,41.0,NaN,NaN,65000.0,116100.0,194500.0,67600.0,NaN,NaN,67600.0,67500.0,112400.0,1996,April
5,1996-04-30,10540,75.0,64200.0,78600.0,106700.0,134700.0,143200.0,102900.0,77500.0,84800.0,102900.0,102800.0,143000.0,1996,April
6,1996-04-30,10580,65.0,62100.0,75900.0,92100.0,126900.0,133500.0,95200.0,69400.0,65400.0,95200.0,95500.0,146800.0,1996,April
7,1996-04-30,10620,44.0,NaN,NaN,77200.0,117000.0,144700.0,70000.0,NaN,NaN,70000.0,70000.0,121600.0,1996,April
8,1996-04-30,10740,64.0,85500.0,94500.0,115400.0,156000.0,195000.0,116000.0,86700.0,93300.0,116000.0,116400.0,169900.0,1996,April
9,1996-04-30,10780,54.0,NaN,66700.0,89500.0,153600.0,NaN,59800.0,NaN,NaN,59800.0,59800.0,107900.0,1996,April
10,1996-04-30,10900,67.0,78700.0,83600.0,98500.0,158000.0,104900.0,108100.0,70800.0,100600.0,108100.0,108400.0,166600.0,1996,April
11,1996-04-30,11020,NaN,NaN,NaN,NaN,NaN,NaN,55000.0,NaN,NaN,55000.0,55000.0,NaN,1996,April
12,1996-04-30,11060,NaN,NaN,NaN,50100.0,NaN,NaN,42400.0,NaN,NaN,42400.0,42400.0,NaN,1996,April
13,1996-04-30,11100,41.0,NaN,NaN,68100.0,118200.0,NaN,64400.0,NaN,52400.0,64400.0,64500.0,NaN,1996,April
14,1996-04-30,11140,26.0,NaN,NaN,NaN,70200.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1996,April
15,1996-04-30,11180,67.0,NaN,NaN,NaN,NaN,118900.0,NaN,NaN,NaN,NaN,NaN,NaN,1996,April
16,1996-04-30,11220,38.0,NaN,48700.0,58500.0,60300.0,61000.0,55800.0,40200.0,NaN,55800.0,55800.0,NaN,1996,April
17,1996-04-30,11420,61.0,62700.0,70000.0,89500.0,NaN,NaN,88500.0,62000.0,NaN,88500.0,88500.0,NaN,1996,April
18,1996-04-30,11460,90.0,89900.0,101700.0,122100.0,182100.0,199900.0,128000.0,92200.0,125300.0,128000.0,128600.0,218000.0,1996,April
19,1996-04-30,11540,56.0,NaN,63900.0,84900.0,104200.0,109700.0,88900.0,62900.0,81500.0,88900.0,88900.0,134300.0,1996,April
20,1996-04-30,11580,NaN,NaN,NaN,NaN,90000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1996,April
21,1996-04-30,11620,NaN,NaN,NaN,NaN,94000.0,NaN,43000.0,NaN,NaN,43000.0,43000.0,85300.0,1996,April
22,1996-04-30,11700,64.0,59300.0,69100.0,105500.0,150700.0,185700.0,89600.0,51600.0,98500.0,89600.0,88100.0,151400.0,1996,April
23,1996-04-30,11740,54.0,58500.0,64400.0,84700.0,99700.0,107400.0,80900.0,52400.0,NaN,80900.0,80600.0,121000.0,1996,April
24,1996-04-30,11780,50.0,NaN,NaN,69100.0,77300.0,NaN,63500.0,NaN,67900.0,63500.0,63600.0,101600.0,1996,April
25,1996-04-30,11820,NaN,NaN,NaN,NaN,NaN,164000.0,NaN,NaN,NaN,NaN,NaN,NaN,1996,April
26,1996-04-30,11940,41.0,NaN,NaN,65800.0,93400.0,NaN,65300.0,40000.0,NaN,65300.0,65400.0,116700.0,1996,April
27,1996-04-30,11980,NaN,NaN,59100.0,NaN,NaN,NaN,NaN,41900.0,NaN,NaN,NaN,NaN,1996,April
28,1996-04-30,12020,52.0,49400.0,61100.0,82200.0,125000.0,170300.0,86300.0,55500.0,66700.0,86300.0,87100.0,154400.0,1996,April
29,1996-04-30,12060,59.0,81700.0,72700.0,95300.0,157500.0,221500.0,106700.0,69200.0,92900.0,106700.0,108000.0,182300.0,1996,April
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210891,2017-12-31,48260,69.0,NaN,NaN,90900.0,106500.0,122000.0,85200.0,NaN,NaN,85200.0,85100.0,132400.0,2017,December
210892,2017-12-31,48300,212.0,250200.0,250700.0,309700.0,370200.0,415600.0,291900.0,211700.0,236500.0,291900.0,300000.0,461300.0,2017,December
210893,2017-12-31,48460,NaN,NaN,NaN,NaN,NaN,NaN,117000.0,78900.0,NaN,117000.0,117000.0,189800.0,2017,December
210894,2017-12-31,48540,72.0,NaN,NaN,103900.0,134900.0,166300.0,91900.0,55300.0,NaN,91900.0,92000.0,158400.0,2017,December
210895,2017-12-31,48580,114.0,NaN,140600.0,190100.0,246900.0,476900.0,197100.0,136900.0,NaN,197100.0,191900.0,354200.0,2017,December
210896,2017-12-31,48620,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75900.0,NaN,NaN,NaN,NaN,2017,December
210897,2017-12-31,48660,NaN,NaN,NaN,NaN,165300.0,245500.0,NaN,NaN,NaN,NaN,NaN,172500.0,2017,December
210898,2017-12-31,48700,100.0,95300.0,118400.0,151800.0,176500.0,173200.0,146800.0,96400.0,NaN,146800.0,146800.0,213900.0,2017,December
210899,2017-12-31,48780,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,288300.0,2017,December
210900,2017-12-31,48820,101.0,NaN,NaN,NaN,232700.0,NaN,163300.0,107100.0,NaN,163300.0,163400.0,NaN,2017,December
210901,2017-12-31,48900,134.0,NaN,145900.0,212500.0,368000.0,520100.0,217800.0,134700.0,174600.0,217800.0,221400.0,394700.0,2017,December
210902,2017-12-31,48940,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017,December
210903,2017-12-31,48980,75.0,NaN,79400.0,123000.0,204000.0,259200.0,124900.0,79100.0,NaN,124900.0,124800.0,204400.0,2017,December
210904,2017-12-31,49020,136.0,103200.0,151400.0,204300.0,315700.0,357500.0,210000.0,137500.0,NaN,210000.0,210000.0,337000.0,2017,December
210905,2017-12-31,49080,134.0,NaN,138700.0,210300.0,300000.0,NaN,193300.0,140600.0,NaN,193300.0,193600.0,302500.0,2017,December
210906,2017-12-31,49100,98.0,96000.0,118300.0,146600.0,171600.0,162200.0,143200.0,113000.0,NaN,143200.0,143200.0,228700.0,2017,December
210907,2017-12-31,49180,85.0,75600.0,83500.0,137500.0,226700.0,323400.0,133100.0,80900.0,95200.0,133100.0,135000.0,227500.0,2017,December
210908,2017-12-31,49220,71.0,NaN,78900.0,115700.0,148600.0,NaN,120000.0,77500.0,NaN,120000.0,120000.0,168500.0,2017,December
210909,2017-12-31,49260,79.0,NaN,NaN,NaN,158700.0,NaN,117000.0,NaN,NaN,117000.0,117000.0,166200.0,2017,December
210910,2017-12-31,49300,101.0,95600.0,117400.0,147500.0,183700.0,228100.0,146600.0,95900.0,126200.0,146600.0,147600.0,222100.0,2017,December
210911,2017-12-31,49340,169.0,151400.0,204200.0,256500.0,374000.0,371200.0,257300.0,176200.0,185400.0,257300.0,265200.0,403300.0,2017,December
210912,2017-12-31,49380,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017,December
210913,2017-12-31,49420,138.0,107300.0,142100.0,205400.0,240300.0,274300.0,189200.0,129400.0,188600.0,189200.0,189300.0,289000.0,2017,December
210914,2017-12-31,49460,NaN,NaN,NaN,NaN,NaN,NaN,163700.0,132500.0,NaN,163700.0,163700.0,NaN,2017,December
210915,2017-12-31,49620,114.0,114100.0,133500.0,165100.0,247400.0,143300.0,167100.0,119300.0,121100.0,167100.0,174300.0,258500.0,2017,December
210916,2017-12-31,49660,64.0,49100.0,55300.0,84200.0,133400.0,134700.0,86900.0,45800.0,119400.0,86900.0,85900.0,162800.0,2017,December
210917,2017-12-31,49700,162.0,173800.0,177400.0,259500.0,309100.0,367600.0,272600.0,191400.0,NaN,272600.0,274100.0,370000.0,2017,December
210918,2017-12-31,49740,102.0,NaN,117000.0,149700.0,213500.0,294800.0,137500.0,106200.0,114400.0,137500.0,140700.0,229100.0,2017,December
210919,2017-12-31,49780,83.0,78900.0,79300.0,122700.0,148300.0,183700.0,114100.0,69000.0,126900.0,114100.0,113500.0,172000.0,2017,December
210920,2017-12-31,49820,73.0,NaN,NaN,NaN,NaN,NaN,94900.0,63200.0,NaN,94900.0,94900.0,167600.0,2017,December

In [35]:
first_grouped_data['CBSACode'] = first_grouped_data['CBSACode'].astype(float)

In [36]:
first_grouped_data['CBSACode'] = first_grouped_data['CBSACode'].astype(int)

In [37]:
first_grouped_data['CBSACode'] = first_grouped_data['CBSACode'].astype('str')

In [38]:
first_grouped_data.dtypes

Year                      object
Month                     object
State                     object
StateFIPS                 object
MetroName_Zillow          object
CBSAName                  object
MetroRegionID_Zillow      object
CBSACode                  object
Unemployment Rate        float64
CountyFIPS               float64
CountyRegionID_Zillow    float64
FIPS                     float64
dtype: object

In [39]:
new_metro_data.dtypes

Date                          datetime64[ns]
CBSACode                              object
ZHVIPerSqft_AllHomes                 float64
ZHVI_1bedroom                        float64
ZHVI_2bedroom                        float64
ZHVI_3bedroom                        float64
ZHVI_4bedroom                        float64
ZHVI_5BedroomOrMore                  float64
ZHVI_AllHomes                        float64
ZHVI_BottomTier                      float64
ZHVI_CondoCoop                       float64
ZHVI_MiddleTier                      float64
ZHVI_SingleFamilyResidence           float64
ZHVI_TopTier                         float64
Year                                  object
Month                                 object
dtype: object

In [89]:
pd.set_option('display.max_columns', 500)

In [90]:
metro_unemployment_zhvi_data = pd.merge(first_grouped_data, new_metro_data)

In [91]:
metro_unemployment_zhvi_data

,Year,Month,State,StateFIPS,MetroName_Zillow,CBSAName,MetroRegionID_Zillow,CBSACode,Unemployment Rate,CountyFIPS,CountyRegionID_Zillow,FIPS,Date,ZHVIPerSqft_AllHomes,ZHVI_1bedroom,ZHVI_2bedroom,ZHVI_3bedroom,ZHVI_4bedroom,ZHVI_5BedroomOrMore,ZHVI_AllHomes,ZHVI_BottomTier,ZHVI_CondoCoop,ZHVI_MiddleTier,ZHVI_SingleFamilyResidence,ZHVI_TopTier
0,1996,April,Maryland,24.0,"Baltimore, MD","Baltimore-Columbia-Towson, MD",394358.0,12580,8.300000,510.000000,3236.000000,24510.000000,1996-04-30,82.0,75500.0,85100.0,110800.0,170300.0,244600.0,118600.0,64700.0,98100.0,118600.0,121600.0,197800.0
1,1996,April,Missouri,29.0,"St. Louis, MO","St. Louis, MO-IL",395121.0,41180,8.400000,510.000000,3269.000000,29510.000000,1996-04-30,64.0,49600.0,61000.0,92200.0,159800.0,208900.0,81500.0,47100.0,75600.0,81500.0,82100.0,147300.0
2,1996,April,Virginia,51.0,"Charlottesville, VA","Charlottesville, VA",394459.0,16820,2.600000,540.000000,3288.000000,51540.000000,1996-04-30,76.0,69500.0,86800.0,109900.0,176800.0,236300.0,112400.0,69800.0,NaN,112400.0,113400.0,207800.0
3,1996,April,Virginia,51.0,"Danville, VA","Danville, VA",394518.0,19260,8.900000,590.000000,3205.000000,51590.000000,1996-04-30,48.0,38700.0,45500.0,69900.0,90600.0,127200.0,61700.0,42200.0,NaN,61700.0,61700.0,99700.0
4,1996,April,Virginia,51.0,"Harrisonburg, VA","Harrisonburg, VA",394668.0,25500,2.100000,660.000000,3273.000000,51660.000000,1996-04-30,66.0,69300.0,73800.0,89100.0,125000.0,144400.0,89600.0,68100.0,NaN,89600.0,90000.0,138500.0
5,1996,April,Virginia,51.0,"Kingsport, TN","Kingsport-Bristol-Bristol, TN-VA",394747.0,28700,4.500000,520.000000,1560.000000,51520.000000,1996-04-30,44.0,NaN,44300.0,69300.0,109200.0,145300.0,65300.0,40700.0,66400.0,65300.0,65300.0,115500.0
6,1996,April,Virginia,51.0,"Lynchburg, VA","Lynchburg, VA",394811.0,31340,3.500000,680.000000,3243.000000,51680.000000,1996-04-30,NaN,NaN,NaN,NaN,NaN,113500.0,NaN,NaN,NaN,NaN,NaN,NaN
7,1996,April,Virginia,51.0,"Martinsville, VA","Martinsville, VA",394836.0,32300,9.800000,690.000000,3276.000000,51690.000000,1996-04-30,45.0,NaN,NaN,NaN,NaN,NaN,53900.0,NaN,NaN,53900.0,53900.0,83100.0
8,1996,April,Virginia,51.0,"Richmond, VA","Richmond, VA",395022.0,40060,6.300000,682.500000,3244.500000,51682.500000,1996-04-30,60.0,61000.0,62300.0,87700.0,137400.0,209100.0,96700.0,61900.0,81700.0,96700.0,97700.0,164800.0
9,1996,April,Virginia,51.0,"Roanoke, VA","Roanoke, VA",395028.0,40220,3.200000,772.500000,1943.500000,51772.500000,1996-04-30,63.0,47400.0,58400.0,86000.0,122400.0,175600.0,81900.0,52500.0,85100.0,81900.0,82000.0,145900.0
10,1996,April,Virginia,51.0,"Staunton, VA","Staunton-Waynesboro, VA",395128.0,44420,4.450000,805.000000,3246.000000,51805.000000,1996-04-30,56.0,58300.0,61200.0,82700.0,118300.0,144800.0,82300.0,55600.0,NaN,82300.0,82300.0,132600.0
11,1996,April,Virginia,51.0,"Virginia Beach, VA","Virginia Beach-Norfolk-Newport News, VA-NC",395194.0,47260,5.166667,725.000000,3233.666667,51725.000000,1996-04-30,61.0,62200.0,68600.0,90500.0,136200.0,197300.0,97100.0,65100.0,78600.0,97100.0,101500.0,165300.0
12,1996,April,Virginia,51.0,"Washington, DC","Washington-Arlington-Alexandria, DC-VA-MD-WV",395209.0,47900,3.166667,619.666667,3244.166667,51619.666667,1996-04-30,96.0,84300.0,112600.0,144000.0,212200.0,269500.0,154200.0,102200.0,123000.0,154200.0,176200.0,250300.0
13,1996,April,Virginia,51.0,"Winchester, VA","Winchester, VA-WV",395232.0,49020,4.100000,840.000000,3263.000000,51840.000000,1996-04-30,59.0,49500.0,65000.0,88100.0,139600.0,159700.0,89500.0,61000.0,NaN,89500.0,89500.0,142800.0
14,1996,August,Maryland,24.0,"Baltimore, MD","Baltimore-Columbia-Towson, MD",394358.0,12580,8.400000,510.000000,3236.000000,24510.000000,1996-08-31,82.0,74800.0,84700.0,110600.0,171100.0,243200.0,118300.0,65100.0,97100.0,118300.0,121200.0,200000.0
15,1996,August,Missouri,29.0,"St. Louis, MO","St. Louis, MO-IL",395121.0,41180,8.600000,510.000000,3269.000000,29510.000000,1996-08-31,64.0,48000.0,61400.0,93200.0,160400.0,204500.0,82300.0,47400.0,75300.0,82300.0,83000.0,148300.0
16,1996,August,Virginia,51.0,"Charlottesville, VA","Charlottesville, VA",394459.0,16820,3.000000,540.000000,3288.000000,51540.000000,1996-08-31,79.0,73700.0,88400.0,113500.0,178300.0,240100.0,115800.0,72000.0,NaN,115800.0,117500.0,210000.0
17,1996,August,Virginia,51.0,"Danville, VA","Danville, VA",394518.0,19260,8.300000,590.000000,3205.000000,51590.000000,1996-08-31,49.0,40200.0,45000.0,72900.0,94300.0,127500.0,64700.0,42000.0,NaN,64700.0,64700.0,106500.0
18,1996,August,Virginia,51.0,"Harrisonburg, VA","Harrisonburg, VA",394668.0,25500,2.200000,660.000000,3273.000000,51660.000000,1996-08-31,66.0,69200.0,73400.0,88800.0,123700.0,141300.0,89000.0,68900.0,NaN,89000.0,89500.0,136600.0
19,1996,August,Virginia,51.0,"Kingsport, TN","Kingsport-Bristol-Bristol, TN-VA",394747.0,28700,6.200000,520.000000,1560.000000,51520.000000,1996-08-31,44.0,NaN,45300.0,70500.0,109200.0,141100.0,65600.0,41200.0,69400.0,65600.0,65500.0,116000.0
20,1996,August,Virginia,51.0,"Lynchburg, VA","Lynchburg, VA",394811.0,31340,3.600000,680.000000,3243.000000,51680.000000,1996-08-31,NaN,NaN,NaN,NaN,NaN,126000.0,NaN,NaN,NaN,NaN,NaN,NaN
21,1996,August,Virginia,51.0,"Martinsville, VA","Martinsville, VA",394836.0,32300,7.400000,690.000000,3276.000000,51690.000000,1996-08-31,46.0,NaN,NaN,NaN,NaN,NaN,56300.0,NaN,NaN,56300.0,56300.0,87900.0
22,1996,August,Virginia,51.0,"Richmond, VA","Richmond, VA",395022.0,40060,6.000000,682.500000,3244.500000,51682.500000,1996-08-31,60.0,60100.0,62200.0,88200.0,137200.0,210800.0,97800.0,61900.0,81800.0,97800.0,99000.0,165700.0
23,1996,August,Virginia,51.0,"Roanoke, VA","Roanoke, VA",395028.0,40220,2.900000,772.500000,1943.500000,51772.500000,1996-08-31,65.0,51500.0,62100.0,88300.0,126700.0,178400.0,83800.0,54700.0,87000.0,83800.0,83800.0,147900.0
24,1996,August,Virginia,51.0,"Staunton, VA","Staunton-Waynesboro, VA",395128.0,44420,4.950000,805.000000,3246.000000,51805.000000,1996-08-31,55.0,59400.0,60300.0,81200.0,119200.0,142200.0,81000.0,54900.0,NaN,81000.0,81000.0,131300.0
25,1996,August,Virginia,51.0,"Virginia Beach, VA","Virginia Beach-Norfolk-Newport News, VA-NC",395194.0,47260,5.266667,725.000000,3233.666667,51725.000000,1996-08-31,61.0,64800.0,68900.0,89700.0,136300.0,194700.0,97500.0,66300.0,78400.0,97500.0,101900.0,164100.0
26,1996,August,Virginia,51.0,"Washington, DC","Washington-Arlington-Alexandria, DC-VA-MD-WV",395209.0,47900,3.933333,619.666667,3244.166667,51619.666667,1996-08-31,95.0,81700.0,113200.0,144600.0,213000.0,266300.0,154200.0,102200.0,122600.0,154200.0,176600.0,249500.0
27,1996,August,Virginia,51.0,"Winchester, VA","Winchester, VA-WV",395232.0,49020,4.500000,840.000000,3263.000000,51840.000000,1996-08-31,56.0,43700.0,60500.0,84200.0,133600.0,151600.0,86100.0,56600.0,NaN,86100.0,86200.0,137000.0
28,1996,December,Maryland,24.0,"Baltimore, MD","Baltimore-Columbia-Towson, MD",394358.0,12580,7.800000,510.000000,3236.000000,24510.000000,1996-12-31,82.0,72800.0,84800.0,111100.0,171100.0,243700.0,118700.0,65000.0,97300.0,118700.0,122200.0,201200.0
29,1996,December,Missouri,29.0,"St. Louis, MO","St. Louis, MO-IL",395121.0,41180,7.600000,510.000000,3269.000000,29510.000000,1996-12-31,64.0,48300.0,61400.0,94300.0,162000.0,206000.0,82900.0,47700.0,76000.0,82900.0,83900.0,150700.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3702,2016,October,Virginia,51.0,"Blacksburg, VA","Blacksburg-Christiansburg-Radford, VA",394392.0,13980,5.400000,750.000000,3182.000000,51750.000000,2016-10-31,100.0,100100.0,NaN,162300.0,259700.0,320000.0,144800.0,93200.0,NaN,144800.0,144800.0,245300.0
3703,2016,October,Virginia,51.0,"Charlottesville, VA","Charlottesville, VA",394459.0,16820,3.400000,540.000000,3288.000000,51540.000000,2016-10-31,166.0,136000.0,181000.0,232600.0,369600.0,508300.0,236900.0,144800.0,165900.0,236900.0,239100.0,423200.0
3704,2016,October,Virginia,51.0,"Danville, VA","Danville, VA",394518.0,19260,5.700000,590.000000,3205.000000,51590.000000,2016-10-31,62.0,40800.0,53200.0,98200.0,132400.0,175000.0,78300.0,40400.0,NaN,78300.0,78300.0,146300.0
3705,2016,October,Virginia,51.0,"Harrisonburg, VA","Harrisonburg, VA",394668.0,25500,5.000000,660.000000,3273.000000,51660.000000,2016-10-31,119.0,152900.0,146600.0,179100.0,238400.0,276400.0,180200.0,134800.0,NaN,180200.0,181500.0,270700.0
3706,2016,October,Virginia,51.0,"Kingsport, TN","Kingsport-Bristol-Bristol, TN-VA",394747.0,28700,5.200000,520.000000,1560.000000,51520.000000,2016-10-31,77.0,75900.0,76900.0,120100.0,184400.0,259600.0,115400.0,67500.0,103000.0,115400.0,116000.0,202100.0
3707,2016,October,Virginia,51.0,"Lynchburg, VA","Lynchburg, VA",394811.0,31340,5.200000,680.000000,3243.000000,51680.000000,2016-10-31,95.0,110000.0,109200.0,142100.0,181600.0,220500.0,141100.0,95600.0,109500.0,141100.0,141500.0,232400.0
3708,2016,October,Virginia,51.0,"Martinsville, VA","Martinsville, VA",394836.0,32300,6.800000,690.000000,3276.000000,51690.000000,2016-10-31,62.0,NaN,NaN,NaN,NaN,NaN,72700.0,54500.0,NaN,72700.0,72700.0,116200.0
3709,2016,October,Virginia,51.0,"Richmond, VA","Richmond, VA",395022.0,40060,5.525000,682.500000,3244.500000,51682.500000,2016-10-31,119.0,129600.0,128700.0,176500.0,270200.0,408400.0,198500.0,124800.0,170800.0,198500.0,200200.0,333000.0
3710,2016,October,Virginia,51.0,"Roanoke, VA","Roanoke, VA",395028.0,40220,4.150000,772.500000,1943.500000,51772.500000,2016-10-31,112.0,96800.0,108500.0,151800.0,219800.0,320700.0,149300.0,98800.0,137000.0,149300.0,150000.0,261500.0
3711,2016,October,Virginia,51.0,"Staunton, VA","Staunton-Waynesboro, VA",395128.0,44420,4.350000,805.000000,3246.000000,51805.000000,2016-10-31,117.0,128900.0,132400.0,174100.0,244300.0,304900.0,172600.0,117900.0,NaN,172600.0,172800.0,294200.0
3712,2016,October,Virginia,51.0,"Virginia Beach, VA","Virginia Beach-Norfolk-Newport News, VA-NC",395194.0,47260,4.922222,725.000000,3233.666667,51725.000000,2016-10-31,128.0,128800.0,143200.0,198000.0,295000.0,416500.0,216700.0,137300.0,168800.0,216700.0,225600.0,354400.0
3713,2016,October,Virginia,51.0,"Washington, DC","Washington-Arlington-Alexandria, DC-VA-MD-WV",395209.0,47900,3.500000,619.666667,3244.166667,51619.666667,2016-10-31,228.0,277700.0,301200.0,368900.0,534300.0,702100.0,375500.0,228600.0,307200.0,375500.0,415200.0,661200.0
3714,2016,October,Virginia,51.0,"Winchester, VA","Winchester, VA-WV",395232.0,49020,4.000000,840.000000,3263.000000,51840.000000,2016-10-31,131.0,107200.0,137100.0,197600.0,316100.0,350700.0,203100.0,127100.0,NaN,203100.0,203100.0,336600.0
3715,2016,September,Maryland,24.0,"Baltimore, MD","Baltimore-Columbia-Towson, MD",394358.0,12580,5.800000,510.000000,3236.000000,24510.000000,2016-09-30,171.0,166000.0,186700.0,232000.0,374600.0,528600.0,252500.0,132700.0,194700.0,252500.0,261000.0,444100.0
3716,2016,September,Missouri,29.0,"St. Louis, MO","St. Louis, MO-IL",395121.0,41180,5.700000,510.000000,3269.000000,29510.000000,2016-09-30,113.0,75500.0,101700.0,167200.0,292500.0,407600.0,146200.0,70400.0,129500.0,146200.0,148400.0,282100.0
3717,2016,September,Nevada,32.0,"Carson City, NV","Carson City, NV",394444.0,16180,5.600000,510.000000,3087.000000,32510.000000,2016-09-30,160.0,NaN,168800.0,239400.0,308200.0,453500.0,246900.0,182200.0,NaN,246900.0,260000.0,NaN
3718,2016,September,Virginia,51.0,"Big Stone Gap, VA","Big Stone Gap, VA",753866.0,13720,6.700000,720.000000,3114.000000,51720.000000,2016-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3719,2016,September,Virginia,51.0,"Blacksburg, VA","Blacksburg-Christiansburg-Radford, VA",394392.0,13980,5.200000,750.000000,3182.000000,51750.000000,2016-09-30,100.0,98600.0,NaN,161900.0,259300.0,321100.0,144500.0,92400.0,NaN,144500.0,144500.0,246300.0
3720,2016,September,Virginia,51.0,"Charlottesville, VA","Charlottesville, VA",394459.0,16820,3.300000,540.000000,3288.000000,51540.000000,2016-09-30,165.0,134800.0,180000.0,231900.0,367700.0,504700.0,236100.0,144200.0,166000.0,236100.0,238200.0,420800.0
3721,2016,September,Virginia,51.0,"Danville, VA","Danville, VA",394518.0,19260,5.800000,590.000000,3205.000000,51590.000000,2016-09-30,63.0,40700.0,53000.0,98400.0,133000.0,174500.0,79000.0,40700.0,NaN,79000.0,79000.0,146000.0
3722,2016,September,Virginia,51.0,"Harrisonburg, VA","Harrisonburg, VA",394668.0,25500,4.800000,660.000000,3273.000000,51660.000000,2016-09-30,119.0,150500.0,145700.0,178400.0,237200.0,275200.0,179300.0,133700.0,NaN,179300.0,180600.0,268600.0
3723,2016,September,Virginia,51.0,"Kingsport, TN","Kingsport-Bristol-Bristol, TN-VA",394747.0,28700,5.400000,520.000000,1560.000000,51520.000000,2016-09-30,76.0,75400.0,77000.0,119400.0,181900.0,257500.0,115500.0,67600.0,103000.0,115500.0,116100.0,201000.0
3724,2016,September,Virginia,51.0,"Lynchburg, VA","Lynchburg, VA",394811.0,31340,5.200000,680.000000,3243.000000,51680.000000,2016-09-30,95.0,110700.0,109300.0,142700.0,182100.0,219600.0,141800.0,95300.0,110400.0,141800.0,142000.0,232900.0
3725,2016,September,Virginia,51.0,"Martinsville, VA","Martinsville, VA",394836.0,32300,6.800000,690.000000,3276.000000,51690.000000,2016-09-30,62.0,NaN,NaN,NaN,NaN,NaN,72900.0,54500.0,NaN,72900.0,72900.0,116400.0
3726,2016,September,Virginia,51.0,"Richmond, VA","Richmond, VA",395022.0,40060,5.625000,682.500000,3244.500000,51682.500000,2016-09-30,118.0,128300.0,128100.0,175400.0,269100.0,407600.0,197200.0,124100.0,169700.0,197200.0,199000.0,331200.0
3727,2016,September,Virginia,51.0,"Roanoke, VA","Roanoke, VA",395028.0,40220,4.100000,772.500000,1943.500000,51772.500000,2016-09-30,112.0,96100.0,108400.0,152000.0,219400.0,320600.0,149600.0,98200.0,137700.0,149600.0,150300.0,261400.0
3728,2016,September,Virginia,51.0,"Staunton, VA","Staunton-Waynesboro, VA",395128.0,44420,4.150000,805.000000,3246.000000,51805.000000,2016-09-30,116.0,127800.0,131500.0,173600.0,243000.0,304200.0,172500.0,117500.0,NaN,172500.0,172500.0,293400.0
3729,2016,September,Virginia,51.0,"Virginia Beach, VA","Virginia Beach-Norfolk-Newport News, VA-NC",395194.0,47260,4.888889,725.000000,3233.666667,51725.000000,2016-09-30,127.0,128900.0,142500.0,197100.0,293800.0,414800.0,215900.0,136800.0,167800.0,215900.0,224500.0,353100.0
3730,2016,September,Virginia,51.0,"Washington, DC","Washington-Arlington-Alexandria, DC-VA-MD-WV",395209.0,47900,3.416667,619.666667,3244.166667,51619.666667,2016-09-30,227.0,276400.0,299900.0,366600.0,531800.0,698500.0,373600.0,226700.0,305800.0,373600.0,413000.0,658100.0
3731,2016,September,Virginia,51.0,"Winchester, VA","Winchester, VA-WV",395232.0,49020,3.900000,840.000000,3263.000000,51840.000000,2016-09-30,131.0,107200.0,136500.0,197100.0,315600.0,349600.0,202300.0,126800.0,NaN,202300.0,202200.0,334800.0

In [92]:
sample_abbreviated_data = test_merge_data[['Date', 'CBSACode', 'Unemployment Rate', 'ZHVI_AllHomes']]

In [93]:
sample_abbreviated_data

           Date CBSACode  Unemployment Rate  ZHVI_AllHomes
0    1996-04-30    12580           8.300000       118600.0
1    1996-04-30    41180           8.400000        81500.0
2    1996-04-30    16820           2.600000       112400.0
3    1996-04-30    19260           8.900000        61700.0
4    1996-04-30    25500           2.100000        89600.0
5    1996-04-30    28700           4.500000        65300.0
6    1996-04-30    31340           3.500000            NaN
7    1996-04-30    32300           9.800000        53900.0
8    1996-04-30    40060           6.300000        96700.0
9    1996-04-30    40220           3.200000        81900.0
10   1996-04-30    44420           4.450000        82300.0
11   1996-04-30    47260           5.166667        97100.0
12   1996-04-30    47900           3.166667       154200.0
13   1996-04-30    49020           4.100000        89500.0
14   1996-08-31    12580           8.400000       118300.0
15   1996-08-31    41180           8.600000        82300.0
16   1996-08-31    16820           3.000000       115800.0
17   1996-08-31    19260           8.300000        64700.0
18   1996-08-31    25500           2.200000        89000.0
19   1996-08-31    28700           6.200000        65600.0
20   1996-08-31    31340           3.600000            NaN
21   1996-08-31    32300           7.400000        56300.0
22   1996-08-31    40060           6.000000        97800.0
23   1996-08-31    40220           2.900000        83800.0
24   1996-08-31    44420           4.950000        81000.0
25   1996-08-31    47260           5.266667        97500.0
26   1996-08-31    47900           3.933333       154200.0
27   1996-08-31    49020           4.500000        86100.0
28   1996-12-31    12580           7.800000       118700.0
29   1996-12-31    41180           7.600000        82900.0
...         ...      ...                ...            ...
3702 2016-10-31    13980           5.400000       144800.0
3703 2016-10-31    16820           3.400000       236900.0
3704 2016-10-31    19260           5.700000        78300.0
3705 2016-10-31    25500           5.000000       180200.0
3706 2016-10-31    28700           5.200000       115400.0
3707 2016-10-31    31340           5.200000       141100.0
3708 2016-10-31    32300           6.800000        72700.0
3709 2016-10-31    40060           5.525000       198500.0
3710 2016-10-31    40220           4.150000       149300.0
3711 2016-10-31    44420           4.350000       172600.0
3712 2016-10-31    47260           4.922222       216700.0
3713 2016-10-31    47900           3.500000       375500.0
3714 2016-10-31    49020           4.000000       203100.0
3715 2016-09-30    12580           5.800000       252500.0
3716 2016-09-30    41180           5.700000       146200.0
3717 2016-09-30    16180           5.600000       246900.0
3718 2016-09-30    13720           6.700000            NaN
3719 2016-09-30    13980           5.200000       144500.0
3720 2016-09-30    16820           3.300000       236100.0
3721 2016-09-30    19260           5.800000        79000.0
3722 2016-09-30    25500           4.800000       179300.0
3723 2016-09-30    28700           5.400000       115500.0
3724 2016-09-30    31340           5.200000       141800.0
3725 2016-09-30    32300           6.800000        72900.0
3726 2016-09-30    40060           5.625000       197200.0
3727 2016-09-30    40220           4.100000       149600.0
3728 2016-09-30    44420           4.150000       172500.0
3729 2016-09-30    47260           4.888889       215900.0
3730 2016-09-30    47900           3.416667       373600.0
3731 2016-09-30    49020           3.900000       202300.0

[3732 rows x 4 columns]